### ISSUE TITLE
Throwing items stack from inventory, while keeping gun in hand converts this items to guns.

### ISSUE THREAD

**Issue by randomei** [ZombieStriker/QualityArmory#1]
When I throw any stack from inventory (by dragging them and dropping out of inventory), while keeping gun in hand, the gun from hand also drops, and on the ground it looks like stack of guns. When I take it - I get this gun with ammo equals the number of items in stack, that was thrown, plus 1. So I can get any amount of ammo, using, for example, cobblestone (sorry for bad English),
P.S. spigot 1.12

**Comment by ZombieStriker** [comment]
Sorry for the late reply: I do not normally check Github.

There have been half a dozen updates since this was first posted. Has the issue been fixed?

**Comment by AsVaidas** [comment]
Yes, this is still an issue. A gun needs to be dropped with Ctrl+q, otherwise it will create a new bugged gun

**Comment by ZombieStriker** [comment]
Are there any errors in the console when you create a bugged gun? If so, can you post them?

If not, can you post the config file, so I can recreate the problem?

**Comment by AsVaidas** [comment]
@ZombieStriker 
`# Controls whether resoucepacks are sent to users. If you do not want any custom textures, set this to false
useDefaultResourcepack: true
UnlimitedPistolAmmo: false
UnlimitedShotgunAmmo: false
UnlimitedRifleAmmo: false
UnlimitedSMGAmmo: false
UnlimitedSniperAmmo: false
UnlimitedRocketAmmo: false
EnableWeaponDurability: true
BulletDetection:
  step: 0.25
BlockBullets:
  door: true
  halfslabs: false
  leaves: false
  water: false
overrideAnvil: false
sendOnJoin: false
enableBulletTrails: true
enableVisableBulletCounts: true
enableReloadingWhenSwapToOffhand: true
gunMaterialType: DIAMOND_HOE
DefaultResoucepackOverride: false
DefaultResoucepack: https://www.dropbox.com/s/uztx0depegg2hat/QualityArmory%201.5.zip?dl=1
IronSightsOnRightCLick: false
Crafting:
  Ammo556: &id001
  - IRON_INGOT,0,1
  - SULPHUR,0,1
  - REDSTONE,0,1
  Ammo9mm: *id001
  AmmoBuckshot: *id001
  AmmoRPG:
  - IRON_INGOT,0,4
  - SULPHUR,0,6
  - REDSTONE,0,1
  p30: &id002
  - IRON_INGOT,0,5
  - REDSTONE,0,2
  MP5K: *id002
  AK47: &id004
  - IRON_INGOT,0,12
  - REDSTONE,0,5
  M16: &id003
  - IRON_INGOT,0,15
  - REDSTONE,0,5
  Remmington: *id003
  RPG:
  - IRON_INGOT,0,32
  - REDSTONE,0,10
  SW1911: *id002
  M40: *id004
  Enfield: &id005
  - IRON_INGOT,0,12
  - GOLD_INGOT,0,2
  - REDSTONE,0,5
  Henry: *id005
  MouserC96: *id002
  FNFal:
  - IRON_INGOT,0,15
  - REDSTONE,0,5
Weapon:
  P30:
    Durability: 500
    Damage: 3
    Price: 500.5
  MP5K:
    Durability: 1000
    Damage: 1
    Price: 800.0
  AK47:
    Durability: 1000
    Damage: 3
    Price: 1000.0
  M16:
    Durability: 1000
    Damage: 3
    Price: 1000.0
  Remmington:
    Durability: 500
    Damage: 1
    Price: 1000.0
  RPG:
    Durability: 100
  SW1911:
    Durability: 500
    Damage: 2
    Price: 600.0
  M40:
    Durability: 500
    Damage: 5
    Price: 1000.0
  Enfield:
    Durability: 500
    Damage: 2
    Price: 500.0
  Henry:
    Durability: 500
    Damage: 3
    Price: 1000.0
  MouserC96:
    Durability: 500
    Damage: 2
    Price: 400.0
  PKP:
    Price: 2000.0
  UMP:
    Price: 1000.0
  FNFal:
    Durability: 1000
    Damage: 1
    Price: 1000.0
  rPG:
    Price: 5000.0
  Grenade:
    Price: 800.0
Bullet-Particle-Type: FLAME
ACCEPTED-BULLET-PARTICLE-VALUES: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Particle.html
Ammo:
  '556':
    Price: 5.0
  9mm:
    Price: 2.0
  Buckshot:
    Price: 50.0
  RPG:
    Price: 100.0
`

And just drop the gun having bullets
