### ISSUE TITLE
How do I change the words "QualityArmory" from prefix? Its not in the languages file?

### ISSUE THREAD

**Issue by TomLewis** [ZombieStriker/QualityArmory#103]
Hello, I need to change the "QualityArmory" name prefix, but its not in the langauges or config, how do I do this?

![Screenshot 2020-08-13 20 23 09](https://user-images.githubusercontent.com/144046/90180478-ec7ac580-dda6-11ea-9514-6da2d827beaf.png)

**Comment by 12emin34** [comment]
IIRC the only way to do this is to edit the plugin

**Comment by Lorenzo0111** [comment]
I’ll release a new update with that new feature
