### ISSUE TITLE
Give Everyone the weapons

### ISSUE THREAD

**Issue by PizzaRules668** [ZombieStriker/QualityArmory#106]
I am trying to give everyone some weapons but a /qa give enfield @a does not work it says That player is not online

**Comment by 12emin34** [comment]
Try typing * or "all" instead of @a

**Comment by ZombieStriker** [comment]
The @A selector only works for default minecraft commands. Unless you use a plugin that re-adds the selectors (Like Psudocommands), you cannot use selectors for plugin commands.
