### ISSUE TITLE
NoSuchMethod exception on ItemMeta.spigot()

### ISSUE THREAD

**Issue by LazoYoung** [ZombieStriker/QualityArmory#11]
Note: I have tested QA v1.1.118 on 1.13.1 spigot server
Both cases are referring to ItemMeta

1. First case ([entire log](https://pastebin.com/1gFtaGBG))
> [09:29:23] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to QualityArmory v1.1.118
> org.bukkit.event.EventException: null
> 	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300) ~[server.jar:git-Bukkit-1cead62]
> ...
> 	at java.lang.Thread.run(Unknown Source) [?:1.8.0_171]
> **Caused by: java.lang.NoSuchMethodError: org.bukkit.inventory.meta.ItemMeta.spigot()Lorg/bukkit/inventory/meta/ItemMeta$Spigot;
> 	at me.zombie_striker.qg.Main.onClick(Main.java:2607) ~[?:?]**
> 	... and more
<br>

2. Second case ([entire log](https://pastebin.com/bWxry2mi))
> [09:29:22] [Server thread/WARN]: [QualityArmory] Task #65 for QualityArmory v1.1.118 generated an exception
> **java.lang.NoSuchMethodError: org.bukkit.inventory.meta.ItemMeta.spigot()Lorg/bukkit/inventory/meta/ItemMeta$Spigot;
> 	at me.zombie_striker.qg.Main$3.run(Main.java:424) ~[?:?]**
>         ... and more

**Comment by ZombieStriker** [comment]
It seems you are running a bukkit server. One of the required methods for QA is the method for making items unbreakable, which is a method added by spigot. Since Spigot is a direct fork of bukkit, you should use spigot instead.

I'll see if I can add a patch for bukkit, but really, the spigot jar or even one of spigots forks should be used instead.

**Comment by LazoYoung** [comment]
Okay I'll see if I was actually using bukkit.

**Comment by LazoYoung** [comment]
You're right, I was running CraftBukkit. Sorry :P
