### ISSUE TITLE
Full auto when Lshift and shoot

### ISSUE THREAD

**Issue by JoJesseGaming** [ZombieStriker/QualityArmory#125]
is there a way i can disable that guns keep shooting when i press shift/shoot.
when i let left mouse go it keeps on going. Maybe i could assign a different key to switch to full auto or something?
Thanks!

**Comment by ZombieStriker** [comment]
Yes, you can disable automatic firing in the gun's yml file.

No, you cannot change the keys at this time. There is not many keys that send information to the server about the player's state, and that is what I use to determine if the player should fire automatically.
