### ISSUE TITLE
Marker Armor Stands can be hit

### ISSUE THREAD

**Issue by Cinder4198** [ZombieStriker/QualityArmory#126]
Marker Armor Stands can be hit by bullets, even though they don't have a hitbox. This is causing an issue with my MythicMobs mob since it's an armor stand with a custom texture, using a different mob as the hitbox, making it immune to bullets.

**Comment by Lorenzo0111** [comment]
They can be hit because they are an entity

**Comment by Lorenzo0111** [comment]
You should create a plugin with a Entity damage listener and with some check you can cancel the event
