### ISSUE TITLE
The players dont get damage, but mobs can

### ISSUE THREAD

**Issue by YTMrDic** [ZombieStriker/QualityArmory#127]
When Im added plugin, im test it on a mobs, animals. All work good, but when I invite my friend to test, he dont get a damage. Help me and what is this?

**Comment by ZombieStriker** [comment]
Do you have any other plugins on the server that could be interfering with QA?

**Comment by YTMrDic** [comment]
I dont know what is plugins. But I get new issue, when I start server 1.16.5, plugin have error and dont start. What is?

**Comment by YTMrDic** [comment]
> Do you have any other plugins on the server that could be interfering with QA?

I dont know what is plugins. But I get new issue, when I start server 1.16.5, plugin have error and dont start. What is?
