### ISSUE TITLE
When right click to zoom is enabled, if player clicks on block, gun will not zoom. If player shoots on and hits damageable, it will not fire

### ISSUE THREAD

**Issue by IgnorantMountaineer** [ZombieStriker/QualityArmory#128]
Lumping two issues together because I feel bad about posting too many issues.

1.As the title says, if right-click to zoom and left click to fire is enabled, the player will not zoom in. This particularly frustrating in close quarters on in tall grass. 

2. In the same mode, if player left clicks to shoot and the player hits an instance of damageable, the gun will not fire. Instead, it will hit the mob with its fist.

Thanks so much for all your hard work ZombieStriker

**Comment by ZombieStriker** [comment]
1) I' ll see if I can fix that.
2) This is an issue with the way packets are detected. When an entity is hit, it does not call the PlayerInteractEvent event that QA uses to detect when a player left clicks. I'm not sure if there is a fix for it.

**Comment by IgnorantMountaineer** [comment]
1. Thanks!
2. Might be a pain depending on your implementaiton but if you're fairly OO oriented maybe not so hard -- EntityDamageByEntity Event 

https://hub.spigotmc.org/javadocs/spigot/org/bukkit/event/entity/EntityDamageByEntityEvent.html

Then check if player is holding gun, you know the rest etc.
