### ISSUE TITLE
Particles have a short distance when firing Homing RPG

### ISSUE THREAD

**Issue by AnriGameS** [ZombieStriker/QualityArmory#130]
I tried using Homing RPG and you need to aim using your crosshair but it's so difficult because the particles stop showing after a short distance so if you want to shoot to medium-large distances you don't know when is your rocket gonna arrive. I've checked the config and I don't understand how can I change this.

**Comment by ZombieStriker** [comment]
This seems to be an issue with base minecraft. Minecraft does not render particles after a certain distance depending on the type of particle being sent. I'll see if there is any way around it, but I don't know if this can be fixed.
