### ISSUE TITLE
[Issuse] Developer API Events

### ISSUE THREAD

**Issue by ImFound** [ZombieStriker/QualityArmory#135]
Hi, I'm trying to do a "death log". Except that if a player kills a person with quality armor, and in the PlayerDeathEvent I request e.getEntity().getKiller(), it returns null. Is there any way to fix it? Could you have an event defining when a player dies due to qualityarmory?

**Comment by Lorenzo0111** [comment]
I've tried with the [EntityDeathEvent](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/event/entity/EntityDeathEvent.html) and it works well for me:
```java
@EventHandler
public void onDeath(EntityDeathEvent event) {
	Player killer = event.getEntity().getKiller();
	ItemStack item = killer.getInventory().getItemInMainHand();
	boolean isGun = QualityArmory.isGun(hand) || QualityArmory.isIronSights(hand));
}
```
