### ISSUE TITLE
API problem!

### ISSUE THREAD

**Issue by Kyumar** [ZombieStriker/QualityArmory#137]
I have a problem with QualityArmory's API. Using them, i can't check if item in hand is a gun. i used all methods 
( QualityArmory.isGun#, QualityArmory.getGun# != null) but without success.

**Comment by Lorenzo0111** [comment]
I've tried with this simple code and it works well for me:

```java
@Override
public boolean onCommand(CommandSender sender, Command command, String label, String[] args)  {
	boolean gun = QualityArmory.isGun(((Player) sender).getInventory().getItemInMainHand());
	sender.sendMessage(ChatColor.AQUA + "Is Gun: " + gun);
	return true;
}
```

**Comment by Kyumar** [comment]
this method doesn't work to me :/

**Comment by Lorenzo0111** [comment]
> 
> 
> this method doesn't work to me :/

Are you using a default gun?

**Comment by Kyumar** [comment]
i'm using ak47

**Comment by Lorenzo0111** [comment]
I can't reproduce it, what server version are you using?
