### ISSUE TITLE
Plugin spams console with errors when i shoot

### ISSUE THREAD

**Issue by AlexXanderGrib** [ZombieStriker/QualityArmory#152]
Issue probably caused by https://github.com/ZombieStriker/PluginConstructorAPI/issues/3

My log :point_right: [`error.log`](https://github.com/ZombieStriker/QualityArmory/files/7149218/error.log)

**Comment by Lorenzo0111** [comment]
What QualityArmory version are you using? Do not say latest

**Comment by Lorenzo0111** [comment]
I'm pretty sure you are using an outdated version.

**Comment by AlexXanderGrib** [comment]
Yep, you released the fix yesterday, but my version of the plugin is a week old. Thanks for pointing this out
