### ISSUE TITLE
Problem with ironsight

### ISSUE THREAD

**Issue by Kyumar** [ZombieStriker/QualityArmory#153]
I need to save the name of the weapon with which you were killed, only that when I kill a player by aiming the item is called the crosshair and it does not appear to be a weapon, how do I save the name of the weapon even though I am aiming?

**Comment by Lorenzo0111** [comment]
I added a method to get the gun the player is using in his hand. It will also work if he is using an ironsight

**Comment by Kyumar** [comment]
the method is getGunInHand# ? It doesn't work. "NoSuchMethodError".

code tried: 
Gun gun = QualityArmory.getGunInHand(killer);
if(gun != null) killer.sendMessage(gun.getName());

**Comment by Lorenzo0111** [comment]
Ofc, I have to release the update

**Comment by Kyumar** [comment]
Ok, thanks

**Comment by Kyumar** [comment]
Hey, do you have news?

**Comment by Lorenzo0111** [comment]
I’ll release it with other fixes tomorrow

**Comment by Kyumar** [comment]
Ok thanks

**Comment by Lorenzo0111** [comment]
Released
