### ISSUE TITLE
Cannot pull up message in hotbar

### ISSUE THREAD

**Issue by KevBoi22** [ZombieStriker/QualityArmory#156]
So when ever I try to shoot a gun, in the console it says," [PluginConstructorAPI] HotBarMessager disabled! Something went wrong with: sendHotBarMessage = Cannot invoke "java.lang.reflect.Constructor.newInstance(Object[])" because "me.zombie_striker.qg.handlers.HotbarMessager.CHATMESSAGE_CONSTRUCTOR" is null."  and I don't know what this means other than the fact that the hotbar message is broken. This bug is happening in Sprigot 1.17.1

**Comment by Lorenzo0111** [comment]
I’m pretty sure you aren’t using the latest version
