### ISSUE TITLE
Configure the explosives' level

### ISSUE THREAD

**Issue by msmo-mason** [ZombieStriker/QualityArmory#163]
The current explosion caused by weapons are just creeper's level.
but weapons like fatman, it shouldn't be that weak, so I suggest to add a value that can control the level of explosion.

**Comment by Lorenzo0111** [comment]
Hello, now you can manage it by editing the explosionRadius inside the gun configuration. By default it is set to a small number for security reasons.

**Comment by wongiong** [comment]
Is that i have to wait till next release?

**Comment by Lorenzo0111** [comment]
Yea,I’ll release it today

**Comment by wongiong** [comment]
Great
