### ISSUE TITLE
Crafting System (Not important)

### ISSUE THREAD

**Issue by WongIong** [ZombieStriker/QualityArmory#177]
With enableCrafting= false, overrideAnvil= true. 
When right click at an Anvil, people who has permission can still open the crafting GUI. Those without permission will receive a message telling them that they are missing permission.

Maybe it would be better to have a value that controls if something is able to craft it or not.

**Comment by Lorenzo0111** [comment]
If you want to totally disable crafting you have to enable the disableCrafting and disable the anvil override. Else you can choose between enabling both(cmd and anvil) or only one of them.
