### ISSUE TITLE
Block breaking system

### ISSUE THREAD

**Issue by WongIong** [ZombieStriker/QualityArmory#179]
I have two suggestions for this.
- [x] DestructableMaterials can be per weapon different. but keeps the global setting. 
- [x] Logging plugins support, such as Coreprotect.

**Comment by WongIong** [comment]
I have heard this from other dev.
but I think it is really a Necessary Feature..

**Comment by Lorenzo0111** [comment]
I’ll talk with the CoreProtect dev and I’ll see what I can

**Comment by WongIong** [comment]
Great!
