### ISSUE TITLE
Residence Plugin Support

### ISSUE THREAD

**Issue by WongIong** [ZombieStriker/QualityArmory#180]
This is really a necessary to public server.

(maybe also in qav?)

**Comment by Lorenzo0111** [comment]
What should the integration do?

**Comment by WongIong** [comment]
QA, should protect blocks inside the residence, entity damage depends on res-flags. At least these two are the most important things.
QAV, vehicles can't get into residence which they have no permissions

**Comment by Lorenzo0111** [comment]
Can you send me the plugin link?

**Comment by WongIong** [comment]
https://www.spigotmc.org/resources/residence-1-7-10-up-to-1-17.11480/
Depend: https://www.spigotmc.org/resources/cmilib.87610/
Download without donation: http://zrips.net/Residence/

**Comment by Lorenzo0111** [comment]
Already implemented

**Comment by WongIong** [comment]
Seems that is still not working, the block inside a residence region still can be broke by guns
also coreprotect has no log for these broken blocks.

**Comment by Lorenzo0111** [comment]
Fixed it
