### ISSUE TITLE
Spartan compatibility

### ISSUE THREAD

**Issue by sujyrokimora** [ZombieStriker/QualityArmory#185]
My anti-cheat says that a person using this is cheating, I talked to spartan dev and, he says to request the dev to make this compatible with this plugin. If you can make this, I would appreciate

**Comment by sujyrokimora** [comment]
> Are you talking about QualityArmory or QualityArmory Vehicles?

QualityArmory
if you use a gun for some time the anti cheat will think you are using killaura and kicks you

**Comment by Lorenzo0111** [comment]
Ok, I'll fix soon
