### ISSUE TITLE
maven

### ISSUE THREAD

**Issue by RoboMWM** [ZombieStriker/QualityArmory#19]
Could you gradlize/mavenize this?

Having a build system would be appreciated.

**Comment by l3st4tPlugins** [comment]
Sorry I'm a bit late, but can't you use jitpack?

**Comment by RoboMWM** [comment]
You can't just use jitpack or any other system and automatically expect it to magically build a jar for you. You have to specify dependencies and the project name and version, etc.

**Comment by RoboMWM** [comment]
jitpack is just a remote repository to host artifacts that use maven/gradle/etc. so others can use them in their maven projects to depend on them.

**Comment by l3st4tPlugins** [comment]
True, I haven't thought about that.
I just used a flatDir repository on Gradle to use this API.
A build system would definitely be appreciated.
