### ISSUE TITLE
[Suggestion] Oraxen resourcepack compatibility

### ISSUE THREAD

**Issue by BookWyrm114** [ZombieStriker/QualityArmory#191]
Hello, I was wondering if you could add an option to allow Qualityarmory to automatically generate the resourcepack inside the Oraxen resourcepack folder if Oraxen is installed, which would really help any servers using oraxen and Qualityarmory, as it would eliminate the need to manually merge the Qualityarmory pack into the Oraxen pack folder when using qualityarmory..

**Comment by Lorenzo0111** [comment]
This is impossible for now. This depends on the oraxen api.
