### ISSUE TITLE
EssentialsX blocks damage

### ISSUE THREAD

**Issue by laughingbacon** [ZombieStriker/QualityArmory#199]
So when i shoot some1 it does dmg then when i try shooting again it dosent do dmg im sure my shots are hitting them. Do u know a solution or have delt with this before because its not working correctly.

**Comment by Lorenzo0111** [comment]
Can you try in a clean server(without other plugins)?

**Comment by laughingbacon** [comment]
Ok yea i will try that

**Comment by laughingbacon** [comment]
without plguins it works but when add it to my server it doesnt work

**Comment by laughingbacon** [comment]
![github](https://user-images.githubusercontent.com/93697510/140404166-1dad0111-1d67-4db1-8134-f201ebcc94f5.PNG)

**Comment by laughingbacon** [comment]
> Can you try in a clean server(without other plugins)?

can u read what i told u thx

**Comment by Lorenzo0111** [comment]
Can you try without essentials?

**Comment by laughingbacon** [comment]
> Can you try without essentials?

ok i will try it out

**Comment by laughingbacon** [comment]
> Can you try without essentials?

so how do i add essentails and not ruin your plugin is there a config i need to do or is it something else???

**Comment by Lorenzo0111** [comment]
I don’t know, I’ll talk with essentials developers to find a fix

**Comment by Lorenzo0111** [comment]
Can you try disabling the teleport invulnerability on the essentials configuration?

**Comment by laughingbacon** [comment]
> Can you try disabling the teleport invulnerability on the essentials configuration?

K

**Comment by laughingbacon** [comment]
> Can you try disabling the teleport invulnerability on the essentials configuration?

ok it works thank you so much ill come back when i find another bug :)
