### ISSUE TITLE
Weapon damage

### ISSUE THREAD

**Issue by Peskdt** [ZombieStriker/QualityArmory#201]
Most of the weapons in the last few weeks of my server are not doing damage correctly, the first shot of any weapon does the damage and then the player (who is shot) goes into a kind of invulnerability, and cannot take any more damage of weapons. (with snipers it doesn't happen). I thought they would be some plugins with respect to pvp like "Combatlogx" and "Siegewar". But I disabled and tested them, and I still have the same problem.

**Comment by Peskdt** [comment]
![imagen](https://user-images.githubusercontent.com/91406867/141254826-864e30f0-d0a2-436c-9687-6fb6a6b9dd17.png)
![imagen](https://user-images.githubusercontent.com/91406867/141254870-6baa1ef4-78d6-48e4-b5d7-29c9efdc8e30.png)

**Comment by Peskdt** [comment]
![imagen](https://user-images.githubusercontent.com/91406867/141255238-fb2ffbc5-88e1-4f17-8750-28b7b3eaf04a.png)
The laser guns and the barret works

**Comment by Lorenzo0111** [comment]
This is caused from EssentialsX. Try reading the conflicts section in the spigot page. It explains how to fix it
