### ISSUE TITLE
Death Message support

### ISSUE THREAD

**Issue by WongIong** [ZombieStriker/QualityArmory#205]
Page: https://www.spigotmc.org/resources/deathmessages.3789/
if you kill someone when you are aiming
the death message says you kill the victim with the "Aiming" item.
if you are not aiming, it says that you just killed the victim without telling the held item.

**Comment by Lorenzo0111** [comment]
You should ask that to them: https://discord.gg/dhJnq7R

**Comment by WongIong** [comment]
Seems that has been fixed somehow.
