### ISSUE TITLE
Problem using also GSit

### ISSUE THREAD

**Issue by Kyumar** [ZombieStriker/QualityArmory#206]
Using GSit plugin, when a player is sitted, you cannot shot with a gun him. I think because gsit spawn an armorstand in the same loc of player for the "sit" or "lay" effect.

**Comment by JaHollYT** [comment]
This Problem also happends with other Plugins like PosePlugin (https://www.spigotmc.org/resources/poseplugin-choose-your-favorite-pose-1-15-2-1-17.76990/).

I think the Problem is, that QualityArmory does not detect correctly, when a player is passenger of an armorstand or something.

**Comment by Lorenzo0111** [comment]
Ok, I'll fix it

**Comment by Lorenzo0111** [comment]
Fixed. I forgot to push the update. I'll do it today.

Sorry for the delay
