### ISSUE TITLE
WorldGuard hook gives erorrs if WorldGuard is not installed

### ISSUE THREAD

**Issue by Tansd123** [ZombieStriker/QualityArmory#208]
![image](https://user-images.githubusercontent.com/80218721/143142911-6951a445-227a-4e6b-807f-8a9fc3790ac1.png)
I cant run plugin

**Comment by Lorenzo0111** [comment]
Do you have WorldGuard installed?

**Comment by JustAMinecrafter** [comment]
Why are u even using 1.12.2 server?
