### ISSUE TITLE
[Bug] Use colors in custom language

### ISSUE THREAD

**Issue by rewsdjad1** [ZombieStriker/QualityArmory#229]
I run this latest version of this plugin on the latest version of paper 1.16.5, and have enabled EnableWeaponDurability in config, but after enabling this system, the gun cannot shoot, even if the durability of the gun is 1000/1000 and the number of bullets is not 0, you  When firing, the gun will have a sound of insufficient durability instead of a sound of insufficient bullets.  I have tried to enable debug to find the error. The debug message indicates that the durability of the weapon is less than 0. I have tested that this has nothing to do with the number of bullets, and there is no error in the console.  When I turn off EnableWeaponDurability in config, the gun can fire normally.

Also, there is another problem. I opened the Q key reloading system in the config, but when I press Q, the gun cannot be dropped, but the bullets are not reloaded too. At this time, press the right button or F can normally load bullets.

Sorry about my grammar, I used machine translation.

**Comment by Lorenzo0111** [comment]
It works fine for me, what gun are you using?

**Comment by rewsdjad1** [comment]
> @rewsdjad1 It works fine for me, what gun are you using?

All guns are like this

**Comment by Lorenzo0111** [comment]
> > @rewsdjad1 It works fine for me, what gun are you using?
> 
> All guns are like this

What server and plugin version? (Don’t say latest)

**Comment by rewsdjad1** [comment]
> > > @rewsdjad1 It works fine for me, what gun are you using?
> > 
> > 
> > All guns are like this
> 
> What server and plugin version? (Don’t say latest)

the plugin is 2.0.4，the server is paper 1.16.5-792

**Comment by Lorenzo0111** [comment]
can you try reinstalling qualityarmory?

**Comment by rewsdjad1** [comment]
> can you try reinstalling qualityarmory?

Just tried it, even the latest 2.0.5 still has this problem

**Comment by Lorenzo0111** [comment]
Can you send me a screenshot of the item lore?

**Comment by rewsdjad1** [comment]
> Can you send me a screenshot of the item lore?

I found the problem. It seems that the problem was caused by the change of the language. After I changed the language to the original English, the endurance system can be used.

**Comment by rewsdjad1** [comment]
The problem is here. I used color fonts on the "lore_durib" in the language file. If you don't use color fonts, it can detect durability normally.  

In addition, the gun will not automatically replace its lore every time you modify the language file, which will also cause the gun to not fire normally.

**Comment by rewsdjad1** [comment]
Now I have another question. I added a color font to the “reloading” and “ammo” in the language file.  But when I use the guns, the color font is not displayed normally.

![73704DE9-45BF-44AA-9D97-4D1AC0CF3EA7](https://user-images.githubusercontent.com/79432245/148505296-0bf410b9-f4cd-41a5-80d0-7acf4abd6880.jpeg)

![885678AF-BE51-465C-B842-422CBBFA1309](https://user-images.githubusercontent.com/79432245/148505317-c192cb20-6f2c-4dae-a006-1ad216aa54ed.jpeg)

**Comment by Lorenzo0111** [comment]
Try using normal color codes(&)

**Comment by Lorenzo0111** [comment]
> > Can you send me a screenshot of the item lore?
> 
> 
> 
> I found the problem. It seems that the problem was caused by the change of the language. After I changed the language to the original English, the durability system starts to working.

I moved it in #241. I'll fix soon

**Comment by rewsdjad1** [comment]
> Try using normal color codes(&)

No, they still don’t work

**Comment by Lorenzo0111** [comment]
ok

**Comment by rewsdjad1** [comment]
> ok

is there any solution?

**Comment by Lorenzo0111** [comment]
That’s a bug. I’ll fix it soon

**Comment by Lorenzo0111** [comment]
Can you send me your configuration as text? Paste it to paste.lorenzo0111.me

**Comment by rewsdjad1** [comment]
> Can you send me your configuration as text? Paste it to paste.lorenzo0111.me

Sorry for taking so long to reply, I recently reset my PC so I reconfigured the QualityArmory and so far the colors are all working fine.

But it keeps getting error in console now
https://paste.lorenzo0111.me/ozoliqeciw.properties
