### ISSUE TITLE
ViaVersion resource packs

### ISSUE THREAD

**Issue by vlcik128** [ZombieStriker/QualityArmory#23]
Hello.
I have encountered a very annoying problem. 
I am using 1.9.4 spigot server with viaversion 1.6.0 and 1.9.4 client. 
Whenever ViaVersion plugin is enabled on my server and I also have downloaded **server resource pack,** textures of weapons are kinda broken. 
For example, in the weapons shop, I just can see only this gun: [https://imgur.com/cIxFNH7](url)
But, with client resource pack it really works very fine. 

Could you fix it, please? 
I am not so active on GitHub to quickly respond to your questions about this issue, so for more information or questions, please contact me on Discord: vlcik(128);#6159

**Comment by thonking3** [comment]
Me too, it's only have 1 gun, you can give me the link to download cient resource pack, please?

**Comment by thonking3** [comment]
And author, please check it :(

**Comment by Lorenzo0111** [comment]
That’s not a problem on our end
