### ISSUE TITLE
quartz texture not showing in resource pack

### ISSUE THREAD

**Issue by SideLo98** [ZombieStriker/QualityArmory#231]
it's showing something pink/black
![image](https://user-images.githubusercontent.com/67060780/147023918-34024d43-f291-491b-8fa6-356f22d9ab13.png)

**Comment by Lorenzo0111** [comment]
I know and I have to update the default pack.
Just set your pack to https://github.com/ZombieStriker/Qu...ck/releases/download/v2.1.9/QualityArmory.zip
