### ISSUE TITLE
An error

### ISSUE THREAD

**Issue by WongIong** [ZombieStriker/QualityArmory#243]
https://pastebin.com/NT5nn4VF
https://pastebin.com/C1xeGqbW
https://pastebin.com/4gijYGra

**Comment by Lorenzo0111** [comment]
your jar seems to be corrupted, try downloading it again

**Comment by Lorenzo0111** [comment]
Also please use qa 2.0.5.1

**Comment by WongIong** [comment]
i have seen the changelog of 2.0.5.1, so i will update to that version
