### ISSUE TITLE
Overrided all Guns

### ISSUE THREAD

**Issue by WongIong** [ZombieStriker/QualityArmory#246]
Updated to 2.0.5.1
All of the guns' config have been reset
Included prices, translates

It is really a terrible thing

**Comment by Lorenzo0111** [comment]
Luckilly I can't reproduce it. Can you try again?

**Comment by Lorenzo0111** [comment]
Remember to disable Enable_Creation_Of_Default_Files

**Comment by WongIong** [comment]
Its ok now
