### ISSUE TITLE
Ammo Bag

### ISSUE THREAD

**Issue by WongIong** [ZombieStriker/QualityArmory#249]
I have an idea which is adding a bag to storage ammos. 
but shouldn't be too big, like 9 slots is enough. (or it can be permission depends.)

Players can reload their guns by using the ammos inside the bag.
Side effect would be lower the reload speed, aka longer the reload time.

**Comment by WongIong** [comment]
When will this version be released?

**Comment by Lorenzo0111** [comment]
As soon as possible

**Comment by WongIong** [comment]
great
