### ISSUE TITLE
Weapons do not damage players

### ISSUE THREAD

**Issue by StonFlip** [ZombieStriker/QualityArmory#250]
Weapons do not damage players. Weapons only damage animals or monsters.

Sorry for the English, **I am using google translate.**

- config:  **https://pastebin.com/sgtAQTfv**
- plugins:  **https://pastebin.com/ErH52PUg**

**Comment by Lorenzo0111** [comment]
Your paste is private

**Comment by Lorenzo0111** [comment]
Are you running towny on your server?

**Comment by StonFlip** [comment]
> Are you running towny on your server?

Yes, new paste: https://pastebin.com/3vUhTQKM

**Comment by Lorenzo0111** [comment]
Update towny. If the problem persists add "hooks.Towny: false” in the config

**Comment by StonFlip** [comment]
I'm using the latest version of Towny and I added "hooks.Towny: false" to the plugin config, but it didn't help. The weapon still does not damage

**Comment by Lorenzo0111** [comment]
Do you have essentials on your server?

**Comment by StonFlip** [comment]
> Do you have essentials on your server?

Yes, I uploaded the list of all plugins to pastebin and dropped the link just above

**Comment by Lorenzo0111** [comment]
change teleport_vulnerability from 4 to 0 in the EssentialsX config

**Comment by StonFlip** [comment]
> change teleport_vulnerability from 4 to 0 in the EssentialsX config

It did not help

**Comment by Lorenzo0111** [comment]
Can you try to reproduce the issue in a server without other plugins?

**Comment by StonFlip** [comment]
I tried it, it worked, I only installed this plugin and the weapon did damage, but on the main server I cannot experiment with plugins

**Comment by StonFlip** [comment]
Oops .. Sorry, but I tried adding "hooks.Towny: false" to Towny config and it helped ... before that I added "hooks.Towny: false" to QualityArmory config .. Forgive me for wasting time again.

**Comment by Lorenzo0111** [comment]
It’s impossible. That is a QualityArmory option, not a towny one
