### ISSUE TITLE
Towny API is changed and it doesn't work anymore with QA

### ISSUE THREAD

**Issue by Felson999** [ZombieStriker/QualityArmory#256]
See TownyAdvanced/Towny#5635

**Comment by Felson999** [comment]
We really need a fix for it, and it would be great if you do it quick. Our players are waiting for our server, and we can't open it without this fix. Please, please, please 🥺👉🏻👈🏻

**Comment by SideLo98** [comment]
I was having similar issues but it's fixed after updating to latest QA and latest towny version, can you do /plugins -v and send the screenshot ?

**Comment by Felson999** [comment]
> I was having similar issues but it's fixed after updating to latest QA and latest towny version, can you do /plugins -v and send the screenshot ? and if you are using essentials it could be that as well

![image](https://user-images.githubusercontent.com/52543528/149654201-883b9ec5-8f96-4c33-8cc3-681dfadf35e1.png)

**Comment by Lorenzo0111** [comment]
does this happen in a towny world?

**Comment by Felson999** [comment]
![2022-01-16_19 41 41](https://user-images.githubusercontent.com/52543528/149671419-4246e187-9f8b-4c85-a8cf-8b28422584aa.png)

**Comment by Felson999** [comment]
By the way, simple pvp works (hands, swords)

**Comment by Lorenzo0111** [comment]
This is not a solution because this only totally ignores towny, the hook still not work
