### ISSUE TITLE
Light Sword BUG

### ISSUE THREAD

**Issue by WongIong** [ZombieStriker/QualityArmory#258]
I have set the damage to 6, but it appears like only 1 damage

**Comment by Lorenzo0111** [comment]
What lightsaber color are you using?

**Comment by WongIong** [comment]
all type of them.

**Comment by Lorenzo0111** [comment]
It works for me. Are you disabling the default file creation in the config.yml?

**Comment by WongIong** [comment]
Yes i have disabled it.
but it worked before and not working now, didn't change anything in the file.

**Comment by Lorenzo0111** [comment]
Can you try in a clean server with the default configuration?

**Comment by WongIong** [comment]
It works now..
seems this happens randomly.
