### ISSUE TITLE
Reload Bug

### ISSUE THREAD

**Issue by phatrick17** [ZombieStriker/QualityArmory#259]
Players are able to queue reload while firing automatic weapons, which can result in a pseudo-unlimited clip size.

https://streamable.com/5p2zw4

**Comment by Lorenzo0111** [comment]
What gun is it?

**Comment by phatrick17** [comment]
> What gun is it?

Any weapon. Actually even semi auto you can right click during firing and you begin to reload while still firing. It seems like reloading doesn’t lock the player from shooting the weapon

**Comment by Lorenzo0111** [comment]
It works fine for me. Are you using some custom gun? If yes can you send me your gun configuration? Also your config.yml would be appreciated.

**Comment by phatrick17** [comment]
No problem

**Comment by phatrick17** [comment]
name: machinepistol
displayname: '&6Machine Pistol'
id: 50
variant: 0
craftingRequirements:
- IRON_INGOT,0,15
- REDSTONE,0,5
weapontype: SMG
weaponsounds: bulletsmallauto
enableIronSights: false
ammotype: 9mm
damage: 1
maxbullets: 50
lore:
- '&eRarity: ⭐⭐'
price: 1600
material: CROSSBOW
firerate: 4
isAutomatic: true
invalid: false
durability: 5000
maxItemStack: 1
setZoomLevel: 0
sway:
  defaultValue: 0.1
  defaultMultiplier: 1.75
  sneakModifier: true
  moveModifier: true
  runModifier: true
  unscopedModifier: 1
delayForReload: 1.5
delayForShoot: 0.3
bullets-per-shot: 1
maxBulletDistance: 200
unlimitedAmmo: false
LightLeveOnShoot: 14
recoil: 1
slownessOnEquip: 0
particles:
  bullet_particle: REDSTONE
  bullet_particleR: 1
  bullet_particleG: 1
  bullet_particleB: 1
  bullet_particleData: 0
  bullet_particleMaterial: COAL_BLOCK
Version_18_Support: false
ChargingHandler: none
ReloadingHandler: none
addMuzzleSmoke: true
drop-glow-color: none
headshotMultiplier: 1.75
weaponsounds_volume: 4
firing_knockback: 0.2
KilledByMessage: '%player% was shot by %killer% using a %name%'
DestructableMaterials:
- MATERIAL_NAME_HERE
lastModifiedByQA: 1641867934175

**Comment by phatrick17** [comment]
ENABLE-DEBUG: false
language: en
FriendlyFireEnabled: false
KickPlayerIfDeniedResourcepack: false
useDefaultResourcepack: true
EnableWeaponDurability: true
BulletDetection:
  step: 0.1
BlockBullets:
  door: true
  halfslabs: false
  leaves: true
  water: false
  glass: true
enableInteract:
  Chests: false
overrideAnvil: true
showPossibleCrashHelpMessage: true
verboseItemLogging: false
enable_permssionsToShoot: false
sendOnJoin: true
sendTitleOnJoin: false
SecondsTillRPIsSent: 5.0
enableBulletTrails: true
BulletTrailsSpacing: 0.5
enableIgnoreArmorProtection: false
enableIgnoreUnbreakingChecks: false
enableIgnoreSkipForBasegameItems: false
Items:
  enable_Unbreaking: true
enableReloadingOnDrop: false
enableReloadingWhenSwapToOffhand: true
enableReloadOnlyWhenSwapToOffhand: false
allowGunHitEntities: false
showOutOfAmmoOnTitle: false
showReloadingTitle: false
showAmmoInXPBar: false
enableExplosionDamage: false
enableExplosionDamageDrop: false
enablePrimaryWeaponLimiter: false
weaponlimiter_primaries: 2
weaponlimiter_secondaries: 2
enableCrafting: false
enableShop: false
AUTO-UPDATE: true
Swap-Reload-and-Shooting-Controls: false
Order-Shop-By-Price: false
enable_lore_gun-info_messages: true
enable_lore_control-help_messages: true
Enable_Headshot_Instantkill: false
Enable_Headshot_Notification_Sound: true
Headshot_Notification_Sound: entity.experience_orb.pickup
Enable_Headshot_Sounds: true
Enable_AutoArm_Grenades: false
gravityConstantForDropoffCalculations: 0.05
allowGunReload: true
Auto-Detect-Resourcepack: true
ManuallyOverrideTo_1_8_systems: false
ManuallyOverrideTo_1_13_systems: false
ManuallyOverrideTo_1_14_systems: false
unknownTranslationKeyFixer: false
Enable_Creation_Of_Default_Files: false
EnableGlowEffects: false
Break-Block-Texture-If-Shot: true
enableRecoil: true
experimental:
  BulletWounds:
    InitialBloodLevel: 1500.0
    BloodIncreasePerSecond: 0.01
    Medkit_Heal_Bloodloss_Rate: 0.05
    enableBleeding: false
disableHotbarMessages:
  OutOfAmmo: true
  Shoot: false
  Reload: false
automaticallyReloadGunWhenOutOfAmmo: true
generalModifiers:
  sway:
    Run: 2.0
    Walk: 1.5
    Ironsights: 0.8
    Sneak: 0.7
deathmessages:
  enable: true
impenetrableEntityTypes:
- ARROW
DefaultResourcepackOverride: false
IronSightsOnRightClick: false
SwapSneakToSingleFire: false
DestructableMaterials:
- MATERIAL_NAME_HERE
overrideAttackSpeed: true
DefaultResourcepack: https://github.com/ZombieStriker/QualityArmory-Resourcepack/releases/download/v2.1.9/QualityArmory.zip

**Comment by phatrick17** [comment]
hmmm that didn't format too well...I'll upload the yml files as TXT since it won't let me upload the YMLs lol.
[config.txt](https://github.com/ZombieStriker/QualityArmory/files/7884570/config.txt)
[Machine Pistol.txt](https://github.com/ZombieStriker/QualityArmory/files/7884571/Machine.Pistol.txt)

**Comment by phatrick17** [comment]
So it seems if enabledIronSights = false, you are able to do this bug.
