### ISSUE TITLE
[Bug]: I can't use guns in a world guard region

### ISSUE THREAD

**Issue by Saiserk** [ZombieStriker/QualityArmory#263]
### Confirmations

- [X] I am using the latest plugin version with the required dependencies.
- [X] There isn't any open issue that shows my problem

### What happened?

I have a region on my world and can't aim my guns at other players like I can't shoot if pointing at them, also, the sentinel bots can't shoot at people, which seems weird because it was working a couple of days ago and I literally didn't add anything, I have other worlds with regions and guns work there

### Expected Behaviour

we should be able to shoot other players inside the region

### Server Version

1.17.1

**Comment by Lorenzo0111** [comment]
Please provide your server plugins and your qualityarmory configuration

**Comment by GeRmAnAnToNiO124** [comment]
40ServidoresMC, AdvancedRegionMarket, BeautyQuests, Brewery, BuycraftX, ChatSentry, ChestProtect, Citizens, CMILib, CommandCooldown*, CommandWhitelist, ConditionalEvents, CoreProtect, DeathMessages, DeluxeChat, DeluxeChatHex, DeluxeCombat, DeluxeCombat_Addon_WG*, DeluxeMenus, DeluxeTags, dynmap, Elevator, Essentials, EssentialsSpawn, ezAuctions, Factions, FastAsyncWorldEdit (WorldEdit), Gender, GSit, HolographicDisplays, ItemsAdder, JetsAntiAFKPro, JetsMinions, Jobs, JPremium, KixsChatGames, KOTH, LagAssist, LoneLibs, LPX, LuckPerms, MarriageMaster, mcMMO, MobFarmManager, Multiverse-Core, MyCommand, PlaceholderAPI, PlayerVaults, PlugManX (PlugMan), ProCosmetics, PrometheusExporter, ProtectionStones, ProtocolLib, QAWorldGuard, QualityArmory, Rankup, ReviveMe, Shop, ShopGUIPlus, Shopkeepers, ShowItem, spark, SpecializedCrates, TAB, TreeAssist, UltimateAutoRestart, Vault, Vehicles, Verus*, ViaBackwards, ViaVersion, VoidGen, VoteParty, WGEF-Reborn, WorldBorder, WorldGuard, zAuctionHouseV3

**Comment by GeRmAnAnToNiO124** [comment]
[archive-2022-01-26T050626Z.tar.gz](https://github.com/ZombieStriker/QualityArmory/files/7939063/archive-2022-01-26T050626Z.tar.gz)

**Comment by MeesMees1302** [comment]
Hi, I got the same problem. I can't aim or shoot players, npcs and mobs in worldguard areas.

**Comment by Lorenzo0111** [comment]
Set
hooks.WorldGuard: false 
in the configuration file
