### ISSUE TITLE
[Bug]: Ammo duplicate

### ISSUE THREAD

**Issue by WongIong** [ZombieStriker/QualityArmory#266]
### Confirmations

- [X] I am using the latest plugin version with the required dependencies.
- [X] There isn't any open issue that shows my problem

### What happened?

If you die when you were reloading
you will drop ammos on the ground and your gun will be reloaded.
in this case you will get extra few ammos.

Tested with shotgun.

### Expected Behaviour

stop duplicating

### Server Version

Paper 1.17.1 - 404

**Comment by WongIong** [comment]
When will this be released?
Its been a while from last update and we can't wait for the updates

**Comment by Lorenzo0111** [comment]
I don’t know. I’m very busy in these days
