### ISSUE TITLE
[Bug]: If price for a gun is set to -1 you cannot craft it

### ISSUE THREAD

**Issue by SyntaxGenesis** [ZombieStriker/QualityArmory#269]
### Confirmations

- [X] I am using the latest plugin version with the required dependencies.
- [X] There isn't any open issue that shows my problem

### What happened?

If you set the price for a gun to -1 it no longer allows you to craft it even if you have the proper materials

### Expected Behaviour

I believe I should be able to craft a gun without having to sell it using /qa shop

### Server Version

This server is running Purpur version git-Purpur-1428 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 9beb23b on ver/1.17.1) You are running the latest version Previous version: git-Purpur-1288 (MC: 1.17.1)

**Comment by Lorenzo0111** [comment]
I can't reproduce the issue. Can you zip your QualityArmory folder and send it here?
