### ISSUE TITLE
[Bug]: You Cant Shoot At Other People In World Guard

### ISSUE THREAD

**Issue by laughingbacon** [ZombieStriker/QualityArmory#287]
### Confirmations

- [X] I am using the latest plugin version with the required dependencies.
- [X] There isn't any open issue that shows my problem

### What happened?

I Can't shoot at other players in a regioned area you can throw nades and hit people with light sabers but jisut not the gun

### Expected Behaviour

you should be able to shoot other people in a regioned area

### Server Version

1.16.5

**Comment by Lorenzo0111** [comment]
Plugin list?

**Comment by Hyronymos1337** [comment]
![image](https://user-images.githubusercontent.com/44213484/156893577-d7f4c4f7-6d21-4c03-9915-c58a1c3ec64a.png)

**Comment by laughingbacon** [comment]
![plugin](https://user-images.githubusercontent.com/93697510/157327649-bd0482f8-72b2-465d-a9d1-e7b4ad01c0bb.PNG)

**Comment by laughingbacon** [comment]
> 


![](https://user-images.githubusercontent.com/93697510/157327649-bd0482f8-72b2-465d-a9d1-e7b4ad01c0bb.PNG)

**Comment by Lorenzo0111** [comment]
Merged with #263
