### ISSUE TITLE
[Feature]: Set gun damage cause to damaging player

### ISSUE THREAD

**Issue by Galster-dev** [ZombieStriker/QualityArmory#289]
### Confirmations

- [X] There isn't any other PR or issue regarding this.
- [X] This feature does not exist in the latest version.

### What is your request about?

Other

### Description

May be related to #287

Being short, as for now gun do plugin damage calling `EntityDamageEvent` with cause `CUSTOM`. Some plugins, e.g. for newbie protection listen for `EntityDamageByEntityEvent` to only prevent player damage, so they can't protect from guns. But it works kinda weirdly, so add a bug label here, because it seems to work for regular damage but not prevent lethal shots. If this is true, it might be the other issue.

**Comment by Lorenzo0111** [comment]
The plugin doesn't manually call the event, so this is done by bukkit itself.
