### ISSUE TITLE
Conflict with LightAPI?

### ISSUE THREAD

**Issue by spruill7716** [ZombieStriker/QualityArmory#29]
Updated to the latest version of QA with 1.14 support. Whenever I try and use a gun on an entity, the server spams:

[15:01:12] [Server thread/WARN] [net.minecraft.network.NetHandlerPlayServer]: Willy_Donka moved too quickly! -3.9195018459594007,0.0,9.409420384974396

Then is followed by this crash:
https://www.dropbox.com/s/32l3weba52oouyi/GunCrash.txt?dl=0

Just by glancing over the text, I see mentions of both "guns" and the LightAPI plugin. Could this be some sort of conflict?

**Comment by i9hdkill** [comment]
Looks like LightAPI not QA. There was a LightAPI commit after you created this ticket. Try that and look if it fix that issue

**Comment by spruill7716** [comment]
I see the commits but I don't see a released .jar. Is it somewhere I'm not looking?
https://github.com/BeYkeRYkt/LightAPI/commits/5.0

**Comment by i9hdkill** [comment]
You could build it yourself. it's kinda a swamp of forks and version. The version on spigot supports 1.14 but can't find the source. The source on 1git that supports 1.14 has the version number 5.0. Not even sure if this works with the integrated api in QA. Report your issue to the spigot thread maybe

**Comment by spruill7716** [comment]
I'll continue the issue with the LightAPI devs. Appreciate your help.
