### ISSUE TITLE
[Bug]: [Critical] Server crash

### ISSUE THREAD

**Issue by Hyronymos1337** [ZombieStriker/QualityArmory#290]
### Confirmations

- [X] I am using the latest plugin version with the required dependencies.
- [X] There isn't any open issue that shows my problem

### What happened?

Protocollib Error and Server crash

### Expected Behaviour

no crashes

### Plugins

Protocollib latest

### Server Version

1.18.1

### Relevant log output

```shell
https://pastebin.com/
```

**Comment by Lorenzo0111** [comment]
I need your full server log

**Comment by Hyronymos1337** [comment]
https://paste.twerion.net/acanigadid.makefile

@Lorenzo0111

**Comment by Lorenzo0111** [comment]
This is not caused by QualityArmory. Maybe the server is out of ram?
