### ISSUE TITLE
[Bug]: QAWeaponDamageEntityEvent don't get fired

### ISSUE THREAD

**Issue by ImFound** [ZombieStriker/QualityArmory#292]
### Confirmations

- [X] I am using the latest plugin version with the required dependencies.
- [X] There isn't any open issue that shows my problem

### What happened?

I tried to use the qaweapondamageentityevent to make a thing, but the event is not fired even while I shoot another player.

### Expected Behaviour

get event fired (?)

### Plugins

QualityArmory, SparklessWounds (Plugin for my customer)

### Server Version

[18:01:07 INFO]: Checking version, please wait... [18:01:07 INFO]: This server is running Paper version git-Paper-794 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT) You are running the latest version

**Comment by Lorenzo0111** [comment]
I can't reproduce it. Can you send me the code that you're using? What gun are you using?

**Comment by DextralityNetwork** [comment]
I have the same issue

**Comment by Lorenzo0111** [comment]
> I can't reproduce it. Can you send me the code that you're using? What gun are you using?

Still waiting for these data.

**Comment by JaHollTV** [comment]
Hey there: We use 1.20.1 and the latest devbuild. We have the same issue.
So actually all QA-Events are not get fired.

``
 @EventHandler
    public void onShoot(QAWeaponDamageEntityEvent event) {
        Bukkit.getLogger().info("Dama entity");
        .......
``

**Comment by Lorenzo0111** [comment]
Is #528 fixing this? @JaHollTV

**Comment by JaHollTV** [comment]
yes :)
