### ISSUE TITLE
[Bug]: Error with Protocollib

### ISSUE THREAD

**Issue by lordhadow1** [ZombieStriker/QualityArmory#305]
### Confirmations

- [X] I am using the latest plugin version with the required dependencies.
- [X] There isn't any open issue that shows my problem

### What happened?

Error (yes im using newest version)

### Expected Behaviour

https://privatebin.net/?a21c845b099a9cba#AtqUEr9wfN4hMcyyaYDFZWFdrH6ups7AwdUJbGv5Wpy8

### Plugins

Protocollib latest

### Server Version

1.18.2

**Comment by totKing** [comment]
https://www.toptal.com/developers/hastebin/xegovoqife.csharp
https://www.toptal.com/developers/hastebin/celifivuba.csharp

Your paste is running out - here is another new paste.

**Comment by Lorenzo0111** [comment]
The logs are expired
