### ISSUE TITLE
Bedrock Resource Pack

### ISSUE THREAD

**Issue by BobtheBob123456** [ZombieStriker/QualityArmory#313]
### Confirmations

- [X] There isn't any other PR or issue regarding this.
- [X] This feature does not exist in the latest version.

### What is your request about?

Other

### Description

Hello,
So basically, we play on a geyser server, and as such, the bedrock players cannot see textures. Can we please have a bedrock version of the resource pack?

Thanks.

**Comment by BobtheBob123456** [comment]
Does anyone even look at these? Also, I really need that pack.

**Comment by BobtheBob123456** [comment]
Anyone there

**Comment by Lorenzo0111** [comment]
Hey, we don't officially support geyser so you need to use a converter to convert the resourcepack. Try using one like https://rtm516.github.io/ConvertJavaTextureToBedrock/
