### ISSUE TITLE
[BUG] Server freezes on startup

### ISSUE THREAD

**Issue by tskopen** [ZombieStriker/QualityArmory#317]
### Confirmations

- [X] I am using the latest plugin version with the required dependencies.
- [X] There isn't any open issue that shows my problem

### What happened?

10.04 14:38:18 [Server] INFO [QualityArmory] It appears you are running WorldGuard. If you want to implement flags you can download the QAWorldGuard addon: https://www.spigotmc.org/resources/96868/

the server doesn't load after that line of text in console

### Expected Behaviour

The plugin stops the server loading fully https://mcpaste.io/8e12f551980d19f7

### Plugins

Worldguard, QA, QAworldguard.

### Server Version

1.18.2 paper (cant do /version cause of bug)

### Relevant log output

```shell
10.04 14:38:18 [Server] INFO [QualityArmory] It appears you are running WorldGuard. If you want to implement flags you can download the QAWorldGuard addon: https://www.spigotmc.org/resources/96868/

full log https://mcpaste.io/8e12f551980d19f7
```

**Comment by tskopen** [comment]
never mind for some reason it took 12 minutes for console to pass that messgae and continue loading. so it works now i guess

**Comment by tskopen** [comment]
reopening it happened again but it took like 50 minutes https://mcpaste.io/cbe109cfd09ad28f

**Comment by tskopen** [comment]
<html><head></head><body>

10.04 17:57:47 [Server] ERROR Error occurred while enabling QualityArmory v2.0.6 (Is it up to date?)
--


<span class="console-date">10.04 17:57:47</span> <span class="console-source-server">[Server]</span> <span class="console-level-info">INFO </span>[QualityArmory] Disabling QualityArmory v2.0.6</body></html>

**Comment by Lorenzo0111** [comment]
Can I ask what host are you using to run the plugin?

**Comment by tskopen** [comment]
pebblehost, I think I figured it out. it didn't have enough ram/heap space to fully set up cause I reset the world.
