### ISSUE TITLE
Guns swaying wrong direction

### ISSUE THREAD

**Issue by TheE1337** [ZombieStriker/QualityArmory#32]
A weird bug I noticed, nothing game-breaking, but when you ADS, the direction you first move dictates the sway for the entire time you stay ADSd. For example, if you ADS and move left, the gun will move right, like it should, but then if you change direction without de-ADSing, the gun will still sway to the right.

**Comment by ZombieStriker** [comment]
First, by "ADS", do you mean aim-down signs (Shift/Rightclick), or WASD?

As for this issue, the way the model sways is controlled by the client, not the resourcepack. From what I can tell, the model will always sway to the right if you move while Aiming down the sights, or sway in the same way when holding the gun without aiming, so I don't think this can be changed.

**Comment by TheE1337** [comment]
Might be OptiFine I guess.
