### ISSUE TITLE
 [Bugs]: Proxymine only deals damage in a tiny radius.

### ISSUE THREAD

**Issue by PeeeKayy** [ZombieStriker/QualityArmory#325]
### Confirmations

- [X] I am using the latest plugin version with the required dependencies.
- [X] There isn't any open issue that shows my problem

### What happened?

When you activate a proxymine by walking close to it, it'll explode but only deals damage+knockbacks to entities that are in a ~1.5 block radius. 
So when in practical use players walking to the mine would trip it at a default of 5 block radius, it'll explode before players could come close to the damage radius that is ~1.5 blocks and thus deals no damage to the player.

I will deals damage if i step directly on top of it or i throw it around 1 block of my feet

I did try to set the radius value in proxymine.yml down to 1 to compensate to the small damage radius but it still deals no damage when i step in a 1 block radius.

I did recreated this bug on a clean server.

### Expected Behaviour

Proxymine should deals damage in the same radius or larger than the trigger radius so when players trip it, they will be inside the damage radius and get exploded

### Plugins

QualityArmory

### Server Version

Paper 1.18.2

**Comment by dinobossytnew** [comment]
verificado
