### ISSUE TITLE
[Feature]: stop the automatic shot when you release the left click

### ISSUE THREAD

**Issue by tana-to** [ZombieStriker/QualityArmory#336]
### Confirmations

- [X] There isn't any other PR or issue regarding this.
- [X] This feature does not exist in the latest version.

### What is your request about?

New mechanic

### Description

I swapped the sneak and non-sneak shooting mode to be able to titrate in a standing burst, but when I release the right click the automatic tie does not stop. I will therefore tell you that the shot is only when I remain pressed.

**Comment by Lorenzo0111** [comment]
It works for me, could you please send me a video of the bug?
