### ISSUE TITLE
[Bug]:  Damage varies

### ISSUE THREAD

**Issue by Cornboi0** [ZombieStriker/QualityArmory#337]
### Confirmations

- [X] I am using the latest plugin version with the required dependencies.
- [X] There isn't any open issue that shows my problem

### What happened?

So when it is shot at a player the damage can either kill them and break their armor, or do regular damage. But it only happens every now and then. But it should still be fixed.

### Expected Behaviour

I expect it to be able to do the same amount of damage no matter what.

### Plugins

no

### Server Version

1.18.2

### Relevant log output

```shell
no relevant log output
```

**Comment by Lorenzo0111** [comment]
Disable headshots on the config.yml
