### ISSUE TITLE
[Feature]: Add placeholder support

### ISSUE THREAD

**Issue by rewsdjad1** [ZombieStriker/QualityArmory#352]
### Confirmations

- [x] There isn't any other PR or issue regarding this.
- [X] This feature does not exist in the latest version.

### What is your request about?

Other

### Description

Add placeholder support, such as the amount of ammo of the gun the player is holding, the bullet type of the gun currently held, etc.

**Comment by Lorenzo0111** [comment]
Introduced with 63fc261a6bf33e6efb6d705489c319be2057228a
