### ISSUE TITLE
[Bug]: Fatman doesnt destroy blocks

### ISSUE THREAD

**Issue by sawio2001** [ZombieStriker/QualityArmory#358]
### Confirmations

- [X] I am using the latest plugin version with the required dependencies.
- [X] There isn't any open issue that shows my problem

### What happened?

Fatman is not destroying any blocks on 1.19 even if it suppose to.

### Expected Behaviour

destroy blocks

### Plugins

QualityArmory

### Server Version

1.19

**Comment by Lorenzo0111** [comment]
Sorry for the delay, set `enableExplosionDamage` to true in the config.yml.
