### ISSUE TITLE
[Bug]: Craft item

### ISSUE THREAD

**Issue by Marmur2020** [ZombieStriker/QualityArmory#369]
### Confirmations

- [x] I am using the latest plugin version with the required dependencies.
- [X] There isn't any open issue that shows my problem

### What happened?

When crafting an item with more than 64 pieces, it is not crafted

### Expected Behaviour

Will count the items, then take them away, and weapons will be issued

### Plugins

QualityArmory, soft-depends api

### Server Version

1.18.2

### Relevant log output

```shell
[09:27:27 INFO]: [ОРУЖИЕ] [DEBUG] ClickedShop
[09:27:27 INFO]: [ОРУЖИЕ] [DEBUG] Failed to buy/craft Item
[09:27:27 INFO]: [ОРУЖИЕ] [DEBUG] Detected drop: PICKUP_ALL
```

**Comment by Lorenzo0111** [comment]
Can you send me your gun config?

**Comment by Marmur2020** [comment]
> Can you send me your gun config?

https://www.youtube.com/watch?v=3vjPRcn4-n8

**Comment by Lorenzo0111** [comment]
Could you send it as a text?

**Comment by Marmur2020** [comment]
> Could you send it as a text?

If you put 100 resources it is not crafted, in the other case, if you put 64 items, it will craft this item.

**Comment by Lorenzo0111** [comment]
how are you able to put 100 resources in the crafting table?
