### ISSUE TITLE
[Feature]: Build instructions

### ISSUE THREAD

**Issue by MakcNm4ik** [ZombieStriker/QualityArmory#373]
### Confirmations

- [X] There isn't any other PR or issue regarding this.
- [X] This feature does not exist in the latest version.

### What is your request about?

Other

### Description

Please add build instructions to README.md. I tried to build (mvn clean package) but got an error. 

JDK 8

cannot access me.vagdedes.spartan.api.PlayerViolationEvent

**Comment by Lorenzo0111** [comment]
Hey, thanks for opening an issue.
Sorry for the delays in my replies.

In order to compile you need a few additional dependencies, i will push them to github soon

**Comment by Lorenzo0111** [comment]
Waiting for the spartan repo to back online
