### ISSUE TITLE
[Bug]: Weapon durability

### ISSUE THREAD

**Issue by StonFlip** [ZombieStriker/QualityArmory#376]
### Confirmations

- [X] I am using the latest plugin version with the required dependencies.
- [x] There isn't any open issue that shows my problem

### What happened?

Enabled the function EnableWeaponDurability: true
My weapon stopped firing, shooting when you press the LMB makes some kind of sound. I tried to delete the qa folder and there is no such problem in the default configuration, so I will attach the config so as not to reconfigure the config manually from scratch

Please look at the config and help find the problem

### Expected Behaviour

Enabled the function EnableWeaponDurability: true
My weapon stopped firing, shooting when you press the LMB makes some kind of sound. I tried to delete the qa folder and there is no such problem in the default configuration, so I will attach the config so as not to reconfigure the config manually from scratch

Please look at the config and help find the problem

config: https://pastebin.com/WPRGqRBd
video with sound:  https://imgur.com/a/3DDzJJW

### Plugins

https://pastebin.com/U10uDKdj

### Server Version

1.16.5

### Relevant log output

```shell
Not needed
```

**Comment by Lorenzo0111** [comment]
Hey, thanks for opening an issue.
Sorry for the delays in my replies.

Will work on it soon

**Comment by StonFlip** [comment]
i still need help

**Comment by Lorenzo0111** [comment]
I can't reproduce the issue. Is there an error in console?

**Comment by StonFlip** [comment]
> I can't reproduce the issue. Is there an error in console?

There are no errors in the console, just this sound is played and the weapon does not shoot
