### ISSUE TITLE
[Feature]: Per gun permission nodes

### ISSUE THREAD

**Issue by ProdByPengu** [ZombieStriker/QualityArmory#377]
### Confirmations

- [X] There isn't any other PR or issue regarding this.
- [X] This feature does not exist in the latest version.

### What is your request about?

Other

### Description

Could per gun permission nodes be added? For example `qualityarmory.use.glock`. This makes it useful for only allowing certain ranks to use certain guns.

**Comment by Lorenzo0111** [comment]
Hey, thanks for opening an issue.
Sorry for the delays in my replies.

This is already implemented, it should be qualityarmory.usegun.<name>

**Comment by ProdByPengu** [comment]
doesnt work

**Comment by Lorenzo0111** [comment]
could you send me a photo of the permission you are granting?

**Comment by ProdByPengu** [comment]
sorry nevermind, i just had to enable the gun permissions thing in the config. it indeed does work.
