### ISSUE TITLE
[Bug]: Melee + Granates not disabled in forbidden worlds

### ISSUE THREAD

**Issue by AnimeDrache** [ZombieStriker/QualityArmory#395]
### Confirmations

- [X] I am using the latest plugin version with the required dependencies.
- [X] There isn't any open issue that shows my problem

### What happened?

As we talked in discord, here my bug report:

You can disable weapons in any world but granates or lightsabers, spear etc (melee weapons). You can still use them in any world no matter what permission you have, dont have or negated it.

### Expected Behaviour

All guns to be forbidden in any world where you dont give permissions on weapons.

### Plugins

Not required.

### Server Version

paper-1.19.2-210.jar

**Comment by Lorenzo0111** [comment]
What are you using to disable a world?

**Comment by AnimeDrache** [comment]
I did everything your support on discord told me to do. I've disabled worlds inside the plugin config. Which does work for Guns but not on Melees or Granates.

**Comment by Lorenzo0111** [comment]
Can you send your configuration?
