### ISSUE TITLE
Diamond hoe with lore becomes Buckshot

### ISSUE THREAD

**Issue by AsVaidas** [ZombieStriker/QualityArmory#4]
I made a crafting system of my own. With custom level system for items. But hoe with lore becomes buckshot, and players can't use it as hoe.

**Comment by ZombieStriker** [comment]
Can you post your code?

**Comment by ZombieStriker** [comment]
Again, can you post your code?

For QA, whether the hoe is a gun/ammo/misc is determined by the item's durability. If the durability is between 2 and 25, the hoe will turn into one of those objects.

-

**Comment by AsVaidas** [comment]
What part of code do you need to have?
I don't change the hoe durability, I only modify the lore (add text to it, like in the picture)
If you need the code that add the lore, it's very simple:
`ItemStack item = new ItemStack(Material.DIAMOND_HOE)
ItemMeta meta = item.getItemMeta();
meta.setLore(Arrays.asList(
"line1",
"line2",
"etc"));
item.setItemMeta(meta);`
This is the code, anything else that is in there doesn't interact with the hoe, only calculations

**Comment by ZombieStriker** [comment]
I was asking for the code so I could replicate the problem.

I have tested your code above on my server (Spigot 1.12.2), and the hoe never turns to buckshot shells, even when tilling the ground.

Could there be anything else that may be interfering with the plugin? Are you on an older update/ another server architecture? Are there any other plugins on your server?

**Comment by AsVaidas** [comment]
Always newest paper spigot 1.12.2 version
There was a version that didn't do it, only after an update it begin to do this issue
