### ISSUE TITLE
Question about QualityArmory - Vehicles

### ISSUE THREAD

**Issue by PikaMug** [ZombieStriker/QualityArmory#41]
Posting here because the Spigot page for QAV says, "...please report this issue in the Discussions tab or the Github page" but QAV does not have its own Github page.

In reference to https://github.com/PikaMug/Quests/issues/924 one of your QAV users is experiencing a plugin conflict with my plugin, Quests. While in a vehicle, they are unable to perform quests which require them to reach a specific location. I suspect your plugin is either cancelling the PlayerMoveEvent or doing something that does not trigger the event at all.

Please advise on how your plugin handles the PlayerMoveEvent?

**Comment by ZombieStriker** [comment]
Sorry for the long delay.

Because QAV uses armorstands for the player to drive, PlayerMoveEvent is not called. If the player is in a vehicle, you would most likely need to create a runnable to listen every couple of seconds to see if they moved to the right location.
