### ISSUE TITLE
[Bug]: reload will make rename-gun be default name

### ISSUE THREAD

**Issue by minecraft-dripdrop** [ZombieStriker/QualityArmory#416]
### Confirmations

- [X] I am using the latest plugin version with the required dependencies.
- [X] There isn't any open issue that shows my problem

### What happened?

1.A player rename his gun in anvil 
2. when he reload gun,the gun's name become default name

### Expected Behaviour

should save the custom name 

### Plugins

no any other plugins

### Server Version

purpur-1.19.2-1825

**Comment by Lorenzo0111** [comment]
Gun name can't be changed
