### ISSUE TITLE
[Bug]: right click open scope will let offhand item disapper

### ISSUE THREAD

**Issue by minecraft-dripdrop** [ZombieStriker/QualityArmory#417]
### Confirmations

- [X] I am using the latest plugin version with the required dependencies.
- [X] There isn't any open issue that shows my problem

### What happened?

1. A player's inventory is full and his offhand have one item
2. use gun and right click to open scope
3. the offhand item just gone 

if I use sneak to open scope,the offhand item will drop ground

### Expected Behaviour

the item shouldn't disapper

### Plugins

no any other plugins

### Server Version

purpur-1.19.2-1825

**Comment by Lorenzo0111** [comment]
The item should be dropped when this happens.
