### ISSUE TITLE
[Bug]: Ammo/Clip not going down

### ISSUE THREAD

**Issue by Outdated-mc** [ZombieStriker/QualityArmory#418]
### Confirmations

- [X] I am using the latest plugin version with the required dependencies.
- [X] There isn't any open issue that shows my problem

### What happened?

Whenever you crouch with any pistols (aiming in) after shooting 1 bullet, the rest of the bullets with stay making it infinite ammo and yes i do not have infinite ammo enabled. I am also in survival.

https://user-images.githubusercontent.com/61019098/208019954-e362eebf-55af-45b4-aebf-ffb8af7b3dd3.mp4

### Expected Behaviour

The bullets should go down like normal but instead its not 

### Plugins

QualityArmory

### Server Version

1.19.2

**Comment by AjMudrySchybi** [comment]
Hello, i have the same issue on my server, I noticed it only today. Completely new .jar or default folders just do not fix the problem. Thank you for letting me now if its fixed...

**Comment by Outdated-mc** [comment]
> Hello, i have the same issue on my server, I noticed it only today. Completely new .jar or default folders just do not fix the problem. Thank you for letting me now if its fixed...

Yes all you need to do is disable iron sights on pistols and it fixes it

**Comment by Jack200YT** [comment]
Deactivating the IsAutomatic option also stops firing without wasting bullets
