### ISSUE TITLE
Textures of custom weapons won't load

### ISSUE THREAD

**Issue by NSGamer** [ZombieStriker/QualityArmory#42]
As the title says, the weapon itself works but a purple-black cube appears instead of the model. I have the .json and have done everything that the tutorial for new guns says. 
Using version 1.0.14

**Comment by ZombieStriker** [comment]
You said you are using 1.0.14. Do you mean 1.0.14 for QualityArmory**Vehicles,**  or for QualityArmory? If the latter, you are using an **Extremely** outdated version and should use the newest version.
