### ISSUE TITLE
[Bug]: Could not pass event QAWeaponDamageEntityEvent to COM-Warfare v2.15.4

### ISSUE THREAD

**Issue by CiniJr** [ZombieStriker/QualityArmory#435]
### Confirmations

- [X] I am using the latest plugin version with the required dependencies.
- [X] There isn't any open issue that shows my problem

### What happened?

![ProofForQA](https://user-images.githubusercontent.com/13676517/210679224-7b673645-9380-41e3-bb6e-bb3a37c7104d.png)

### Expected Behaviour

![ProofForQA](https://user-images.githubusercontent.com/13676517/210679232-0168434d-c2c7-4add-8347-8ff18240eb88.png)

### Plugins

Quality Armory

### Server Version

1.18.2

**Comment by Lorenzo0111** [comment]
You are using an outdated api version or qa version.
