### ISSUE TITLE
[Bug]: ammo disappears when i aim

### ISSUE THREAD

**Issue by tana-to** [ZombieStriker/QualityArmory#438]
### Confirmations

- [X] I am using the latest plugin version with the required dependencies.
- [X] There isn't any open issue that shows my problem

### What happened?

when I aim with a weapon (with the right click), the ammunition loaded in the weapon disappears so I cannot shoot while aiming

### Expected Behaviour

I should be able to aim and shoot normally, without ammo disappearing.

### Plugins

PluginConstructorAPI, Lobbys, MoonGlasses, PlaceholderAPI, TintHealth, HolographicDisplays, FancyBags, RandomLootChest, CommandHook, HeroTroll, RealTimePlugin, Regen, HideNametag, ViaVersion, NBTAPI, ViaBackwards, LightAPI, LuckPerms, PsudoCommand, SurvivalInvisiframes, PulseHealth, TrollyAchievements, ClearLag, WorldSpawn, BuycraftX, Votifier, ProtocolLib, Gravity, ImageMaps, PrefiX, ImageOnMap, GrapplingHook, AntiBuild, Links, floodgate, Vault, Scoreboard-revision, Vehicles, SkinsRestorer, InfernalMobs, dynmap, WorldEdit, PlayerKits, Essentials, Multiverse-Core, VotingPlugin, VoteListener, AdvancedAchievements, EssentialsChat, WorldGuard, EssentialsProtect, WorldGuardGUI, EssentialsGeoIP, Duels, EssentialsSpawn, WorldGuardExtraFlags, Essentials_WarpGUI, CorpseReborn, MoneyFromMobs, Citizens, Sentinel, MTVehicles, OpenAudioMc, PhatLoots, CommandNPC, QualityArmory, Denizen, BetterRevive

### Server Version

1.16.5

### Relevant log output

```shell
link of the logs (it was too long) : https://mclo.gs/lMjwRJM
```

**Comment by Lorenzo0111** [comment]
Cannot reproduce. Can you record a video?
