### ISSUE TITLE
[Feature]: rpg don't destroy groun only in a specific zone

### ISSUE THREAD

**Issue by tana-to** [ZombieStriker/QualityArmory#439]
### Confirmations

- [X] There isn't any other PR or issue regarding this.
- [X] This feature does not exist in the latest version.

### What is your request about?

New mechanic

### Description

it would be nice to make sure that we can deactivate, only in a certain area, the destruction of the terrain by grenades, rpg and explosions, or the weapons fire. 
for example with the help of world guard.

**Comment by Lorenzo0111** [comment]
You can already do that. The plugin checks for the following worldguard flag: OTHER-EXPLOSION
