### ISSUE TITLE
[Feature]: CrackShotPlus conversion 

### ISSUE THREAD

**Issue by ImYenil** [ZombieStriker/QualityArmory#448]
### Confirmations

- [X] There isn't any other PR or issue regarding this.
- [X] This feature does not exist in the latest version.

### What is your request about?

CrackShotPlus conversion

### Description

Is it possible to add CrackShotPlus conversion? API download is available at https://github.com/WeaponMechanics/MechanicsMain/blob/master/lib/crackshot/CrackShotPlus.jar

**Comment by Lorenzo0111** [comment]
Hello! The plugin already supports crackshot conversion. Just drag the crackshot configurations into the newGuns folder

**Comment by tana-to** [comment]
can i do the opposite ?

**Comment by tana-to** [comment]
yes

**Comment by Lorenzo0111** [comment]
This is something I won't code, you are asking me to code a way to go to the "competition". You should ask to the author of CrackShot.
