### ISSUE TITLE
[Bug]: Problem with the resource pack

### ISSUE THREAD

**Issue by CaptainRexPL** [ZombieStriker/QualityArmory#455]
### Confirmations

- [X] I am using the latest plugin version with the required dependencies.
- [X] There isn't any open issue that shows my problem

### What happened?

Some of the textures of the guns are bugged. I checked if this is a problem with my client, but it's not. It seems like the resource pack got updated on github so I think that the problem is with the dropbox link.

### Expected Behaviour

Correctly looking guns' textures.

### Plugins

The problem is not caused by any sort of incompatibility.

### Server Version

git-paper-386 1.19.3

**Comment by Lorenzo0111** [comment]
We are no longer using the dropbox link, please update to the following: `https://github.com/ZombieStriker/QualityArmory-Resourcepack/releases/download/latest/QualityArmory.zip`
