### ISSUE TITLE
[Bug]: unlimited ammo in autofire mode for some guns

### ISSUE THREAD

**Issue by ProdByPengu** [ZombieStriker/QualityArmory#456]
### Confirmations

- [X] I am using the latest plugin version with the required dependencies.
- [X] There isn't any open issue that shows my problem

### What happened?

when using the glock on the mp5k on auto fire mode or like scoping in, it doesn't use up ammo.

using latest qa version

### Expected Behaviour

for it to use up ammo

### Plugins

na

### Server Version

1.19.2

**Comment by ProdByPengu** [comment]
Nevermind, not the glock, but the mp5k

**Comment by WongIong** [comment]
Have this issue on all guns.

**Comment by Lorenzo0111** [comment]
Are you able to record a video of the issue?

**Comment by WongIong** [comment]
https://youtu.be/gpZuX0T2ZRc
before 7s
you can trigger this bug when your setting is right click to shot

**Comment by Lorenzo0111** [comment]
Did you update to the latest version? I think I already have fixed this issue

**Comment by WongIong** [comment]
Yes i did
I downloaded the file from spigot then and put it in a clean server to test it. But the config was copied from the server.

**Comment by Lorenzo0111** [comment]
Duplicate of #543
