### ISSUE TITLE
[Bug]: #415 is not fixed

### ISSUE THREAD

**Issue by WongIong** [ZombieStriker/QualityArmory#457]
### Confirmations

- [X] I am using the latest plugin version with the required dependencies.
- [X] There isn't any open issue that shows my problem

### What happened?

Bullet was set to 0 when using scope

### Expected Behaviour

it shouldnt set the bullet

### Plugins

no

### Server Version

Paper 1.16.5

**Comment by Lorenzo0111** [comment]
Duplicate of #415
