### ISSUE TITLE
[Bug]: Ammo not used when gun is not the active item in hot bar

### ISSUE THREAD

**Issue by zek2468** [ZombieStriker/QualityArmory#460]
### Confirmations

- [X] I am using the latest plugin version with the required dependencies.
- [X] There isn't any open issue that shows my problem

### What happened?

Guns are reloaded without using ammo.
- Start the reloading process
- halfway through the reloading process switch to a different slot on your hot bar
- wait until the gun doesn't say reloading as its name
- gun will appear unloaded until you fire it once

Video of the bug
[https://www.youtube.com/watch?v=eY-0W2s89BE](https://www.youtube.com/watch?v=eY-0W2s89BE)

### Expected Behaviour

Either to stop the reloading process when not the currently active item in the hot bar
or
to use the ammo when reloading when the gun is not an active item.

### Plugins

AngelChest, AntiAFKPlus, ArmorStandAdjustor, AsyncWorldEdit, BanManager, BanManager-WebEnhancer, Brewery, Cannons, CharacterCards, ClearLag, CMILib, CommandWatcher*, CoreProtect, CustomCrafting, DeluxeMenus, DeluxeTags, DisableVillagerTrade*, DiscordSRV, dynmap, EcoPower, EnchBook, Essentials, EssentialsGeoIP, EssentialsSpawn, ExoticGarden, FreedomChat, HardcoreSlimefun, HeadDatabase, HolographicDisplays, ImageFrame, Jobs, Lands, LibsDisguises, LightAPI, LocketteX, LPC, LuckPerms, MarriageMaster, mcMMO, MergedMob, Multiverse-Core, Multiverse-Inventories, Multiverse-NetherPortals, Multiverse-Portals, MyCommand, NewPlayerWelcome*, OpenInv, Oraxen, Orebfuscator, PlaceholderAPI, PlayerLandsX, PlotSquared, PlugManX (PlugMan), ProtocolLib, PvPToggle, PwnPlantGrowth, QualityArmory, Rankup, Referral, RewardsLite, ServerlistMOTD*, Shop, SimpleSit*, Slimefun, spark, Spartan, SpeedRoads, TAB, TradeSystem, TreeFeller, Vault, ViewDistanceTweaks, Vivecraft-Spigot-Extensions, Votifier, VotingPlugin, WolfyUtilities, WorldBorder, WorldEdit, WorldGuard, WorldGuardExtraFlags

### Server Version

Paper version git-Paper-307 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: 476ef25) You are running the latest version

**Comment by PKolev26** [comment]
I have the same bug, when you reload and switch to other slot, it doesn't take ammo

https://user-images.githubusercontent.com/98152910/226597282-f97ec740-c694-40bb-b9a2-337ed12a05e3.mp4
