### ISSUE TITLE
[Bug]: Quality Armory bypasses Towny

### ISSUE THREAD

**Issue by Texbio** [ZombieStriker/QualityArmory#468]
### Confirmations

- [X] I am using the latest plugin version with the required dependencies.
- [X] There isn't any open issue that shows my problem

### What happened?

Quality armory grenades seem to bypass towny protection?

### Expected Behaviour

Not bypass towny claims

### Plugins

towny, quality armory

### Server Version

Minecraft 1.19.3

**Comment by Lorenzo0111** [comment]
Can you help me by explaining how to reproduce the issuee? How should I create a claim in towny?
