### ISSUE TITLE
[Feature]: Aim Animation

### ISSUE THREAD

**Issue by xCraimax** [ZombieStriker/QualityArmory#470]
### Confirmations

- [X] There isn't any other PR or issue regarding this.
- [X] This feature does not exist in the latest version.

### What is your request about?

New mechanic

### Description

A feature that shows the aiming player as aiming (crossbow animation) to other player.

**Comment by Lorenzo0111** [comment]
Do you have an image or an example?

**Comment by Lorenzo0111** [comment]
Also duplicate of #463. Please use that

**Comment by Lorenzo0111** [comment]
Duplicate of #463. Please use that

**Comment by Lorenzo0111** [comment]
Duplicate of #463
