### ISSUE TITLE
[Bug]: Medkit not working

### ISSUE THREAD

**Issue by Pajik001** [ZombieStriker/QualityArmory#483]
### Confirmations

- [X] I am using the latest plugin version with the required dependencies.
- [X] There isn't any open issue that shows my problem

### What happened?

When you right click you can't heal self

### Expected Behaviour

That medkit will heal you

### Plugins

Reviveme (This one support QA)

### Server Version

1.18.2

### Relevant log output

```shell
invalid: false
name: medkit
displayname: Medkit
lore: []
id: 22
craftingRequirements:
- WHITE_WOOL,0,6
- GOLDEN_APPLE,0,1
price: 10000
material: PHANTOM_MEMBRANE
damage: 9
durability: 1000
MiscType: MEDKIT
lastModifiedByQA: 1681735600004
sound_equip: openbag
sound_meleehit: openbag
weaponsounds: bulletmedium
maxItemStack: 1
ThrowSpeed: 1.5
```

**Comment by Lorenzo0111** [comment]
Are you able to provide a video of the issue?
