### ISSUE TITLE
[Bug]: Burst Rifle has unlimited ammo when not using Iron Sights

### ISSUE THREAD

**Issue by n3wbConscript** [ZombieStriker/QualityArmory#485]
### Confirmations

- [X] I am using the latest plugin version with the required dependencies.
- [X] There isn't any open issue that shows my problem

### What happened?

So, I went in survival mode to test it out first. The M4 Burst right? I shot it once, and it correctly took 3 ammo (this is without Iron Sights), leaving 27 out of the 30. I shot it again, but this time it remained at 27, and nothing changed. I tried it in creative mode, and now it just didn't even take 3 of the bullets at all, it remained at 30.

The video below might be a little low quality, because I used a video compressor on it.

https://user-images.githubusercontent.com/127911733/235547363-50804f24-e7f3-4561-8591-fe009086dc9e.mp4

### Expected Behaviour

I loved what I got, a very configurable and easy to use plugin with firearms. But I just wished there was a little extra customization and options, and less bugs. BUT, that doesn't mean I hate this plugin, because I think this is better than 85% of the gun MODS out there.

### Plugins

Not really anything relevant here

### Server Version

1.19.3

**Comment by sMerAS26** [comment]
hello, were you able to fix it?

**Comment by Lorenzo0111** [comment]
Could you try with [this](https://ci.codemc.io/job/ZombieStriker/job/QualityArmory/4077/artifact/target/QualityArmory.jar) one?
