### ISSUE TITLE
[Bug]: Infinite ammo while aiming

### ISSUE THREAD

**Issue by NoMercyPeace** [ZombieStriker/QualityArmory#495]
### Confirmations

- [X] I am using the latest plugin version with the required dependencies.
- [X] There isn't any open issue that shows my problem

### What happened?

some weapons like: M41PulseRifle while aiming you have unlimited ammo
weapons bug list:
M41PulseRifle
UMP
Pancor Jackhammer
AA-12
VZ.58
FN FAL
Lazer Rifle
Institute Rifle
"Blaster" Pistol
Flamer
RPK
MP5K
SG-553
The other guns work perfectly so

### Expected Behaviour

The weapons should use the ammo while in automatic-fire but they dont

### Plugins

none

### Server Version

1.19.2

**Comment by Lorenzo0111** [comment]
Are you able to provide a video of the bug?
