### ISSUE TITLE
[Bug]: QualityArmory Players not taking damage.

### ISSUE THREAD

**Issue by Sai7506** [ZombieStriker/QualityArmory#498]
### Confirmations

- [X] I am using the latest plugin version with the required dependencies.
- [X] There isn't any open issue that shows my problem

### What happened?

The players don't seem to be taking any damage from guns. For the first shot, the players take damage but when they shoot each other again, they don't.

### Expected Behaviour

With the plugin, the damage should be received everytime someone is hit right.

### Plugins

BetterRTP, BloodNight, EssentialsX, Floodgate, Geyser, GrapplingHook, Graves, GSit, Lib'sDisguises, LuckPerms, Marriage, Morph, Minepacks, MorePluginsCore, MoreArmors, PlaceHolderAPI, ProtocolLib, Robbing, SleepMost, SimpleScore, WorldEdit

### Server Version

Paper 1.19.2  (307)

**Comment by Lorenzo0111** [comment]
Set teleport_vulnerability to 0 in the EssentialsX configuration
