### ISSUE TITLE
[Bug]: Ammo variants don't work.

### ISSUE THREAD

**Issue by TomekHar** [ZombieStriker/QualityArmory#502]
### Confirmations

- [X] I am using the latest plugin version with the required dependencies.
- [X] There isn't any open issue that shows my problem

### What happened?

The plugin doesn't allow variant setting for ammo. The ammo loads into the game but is unable to be used by any weapons.

### Expected Behaviour

In earlier versions, there were no issues with ammo variants. The guns were able to use them.

### Plugins

QA, LightAPI

### Server Version

1.18.2

**Comment by Lorenzo0111** [comment]
Are you able to find the latest version where this thing was working?
