### ISSUE TITLE
[Bug]: endless bug autogun shooting leads to server crash

### ISSUE THREAD

**Issue by FARF12** [ZombieStriker/QualityArmory#508]
### Confirmations

- [X] I am using the latest plugin version with the required dependencies.
- [X] There isn't any open issue that shows my problem

### What happened?

I found that bug in that gun https://pastebin.com/1VM54iuZ
To repeat the bug, you need to fill up inventory with any blocks, and put a weapon in the last one.
As soon as the player starts shooting, the gun starts shooting endlessly, and then the player kicks from the server. And the shooting remains despite the fact that the player is no longer there. Then the server crashes

### Expected Behaviour

-_-

### Plugins

qa,matrix,

### Server Version

1.16.5

**Comment by Lorenzo0111** [comment]
I can't reproduce this issue. Try in a clean server with this [dev build](https://ci.codemc.io/job/ZombieStriker/job/QualityArmory/lastSuccessfulBuild/artifact/target/QualityArmory.jar).
