### ISSUE TITLE
[Bug]: They can use infinite bullets in guns

### ISSUE THREAD

**Issue by Amirmg086** [ZombieStriker/QualityArmory#511]
### Confirmations

- [X] I am using the latest plugin version with the required dependencies.
- [x] There isn't any open issue that shows my problem

### What happened?

They can use infinite arrows in two different modes, which if one knows how to use them will easily have infinite arrows in all weapons.

### Expected Behaviour

The bug should be fixed so they can't use infinite bullets

### Plugins

Quality Armory

### Server Version

1.17.1

**Comment by Lorenzo0111** [comment]
It should be fixed with the latest [dev buiild](https://ci.codemc.io/job/ZombieStriker/job/QualityArmory/lastSuccessfulBuild/artifact/target/QualityArmory.jar), Can you try?

**Comment by Amirmg086** [comment]
1 - If I switch from an inventory with a random slot and after switching the automatic weapon, it fires infinite bullets

https://github.com/ZombieStriker/QualityArmory/assets/132475371/bb032560-8d6d-46ca-a88c-542ca2c8825b

2 - When the inventory is full, they can shoot infinite bullets!

https://github.com/ZombieStriker/QualityArmory/assets/132475371/90099388-d611-4294-9998-d41857cd19c7

3 - some weapons like: M41PulseRifle while aiming you have unlimited ammo
weapons bug list:
M41PulseRifle
UMP
Pancor Jackhammer
AA-12
VZ.58
FN FAL
Lazer Rifle
Institute Rifle
"Blaster" Pistol
Flamer
RPK
MP5K
SG-553

**Comment by Lorenzo0111** [comment]
Should be fixed! Try with [this](https://ci.codemc.io/job/ZombieStriker/job/QualityArmory/4074/artifact/target/QualityArmory.jar). @Amirmg086

**Comment by laughingbacon** [comment]
its not fixed

**Comment by Lorenzo0111** [comment]
Could you try with [this](https://ci.codemc.io/job/ZombieStriker/job/QualityArmory/4077/artifact/target/QualityArmory.jar) one?
