### ISSUE TITLE
[Bug]: everything works as a crossbow

### ISSUE THREAD

**Issue by RafWasTaken** [ZombieStriker/QualityArmory#514]
### Confirmations

- [X] I am using the latest plugin version with the required dependencies.
- [X] There isn't any open issue that shows my problem

### What happened?

everything needs ae crossbow charge up, no full auto, and lmb just hits

### Expected Behaviour

to be guns and not crossbows 💀

### Plugins

Citzens, Griefprevention, GrimAC, LootChest, Sentinel, SkinsRestorer, Voidgen, Worldguard

### Server Version

1.20

### Relevant log output

```shell
-
```

**Comment by RafWasTaken** [comment]
-by "lmb just hits" i mean when doing left mouse button it uses the fist
and yes i didnt mention quality armory in plugins, but it is there

**Comment by Lorenzo0111** [comment]
Are you able to provide a video? Also provide server version

**Comment by Lorenzo0111** [comment]
Didn't notice you are using 1.20. Plugin is not ready yet for that version, consider switching to this dev build: https://ci.codemc.io/job/ZombieStriker/job/QualityArmory/lastSuccessfulBuild/artifact/target/QualityArmory.jar
