### ISSUE TITLE
[Bug]: API is broken

### ISSUE THREAD

**Issue by JaHollTV** [ZombieStriker/QualityArmory#528]
### Confirmations

- [X] I am using the latest plugin version with the required dependencies.
- [X] There isn't any open issue that shows my problem

### What happened?

Events of the API can only be catched by QA itself, not by other Plugins.

Also tested it with a fork of QA. So if i have a event listener in QA it works.
But since the 1.20 update all event listeners in our own plugin are broken.

I just created a new plugin with only a QA Listener:
public class QAListener implements Listener {

    public QAListener(JaHollDEPlugin jaHollDEPlugin) {
        Bukkit.getPluginManager().registerEvents(this, jaHollDEPlugin);
        Bukkit.getLogger().info("REGISTERED QAListener");
    }

    @EventHandler
    public void onPreWeaponShoot(QAWeaponPrepareShootEvent event) {
        Bukkit.getLogger().info("WeaponPrepareShootEvent catched by JaHollDE");
        System.out.println("Event Gun Name: " + event.getGun().getName());
        event.getPlayer().sendMessage("JHDE Event Gun Name: " + event.getGun().getName());
    }
}

The Plugin is registered, but the EventListener is not working

### Expected Behaviour

other plugins should catch the methods

### Plugins

QualityArmory

### Server Version

1.20.1

### Relevant log output

```shell
nothing - see above
```

**Comment by JaHollTV** [comment]
I have absolutely no idea, why in paper 1.20.1 it is not working.

You can reproduce: Create a plugin and listen to a QA Event

**Comment by xCraimax** [comment]
Same problem here.

**Comment by JaHollTV** [comment]
Issue solved:
For Gradle you have to use compileOnly instead of Implementation.
Implementation is broke

**Comment by Lorenzo0111** [comment]
> Issue solved: For Gradle you have to use compileOnly instead of Implementation. Implementation is broke

This is normal.. implementation should not be used when you are depending on an external plugin.
