### ISSUE TITLE
[Bug]: infinite ammo on single shot guns

### ISSUE THREAD

**Issue by WongIong** [ZombieStriker/QualityArmory#529]
### Confirmations

- [X] I am using the latest plugin version with the required dependencies.
- [X] There isn't any open issue that shows my problem

### What happened?

ammo wouldn't be taken when they shot while zooming
This bug only happens on those gun which has only one ammo and also have scope, such as Homing RPG

### Expected Behaviour

plugin will decrease the ammo amount

### Plugins

no

### Server Version

Paper 1.16.5

**Comment by JaHollTV** [comment]
Same here: **Bug is urgent!!** Newest QA Version.

Reproduce:
1) Take a gun which can aim
2) Aim
3) Shoot while aiming
4) Press the Reload-Key (Swap to off hand) once (gun is not reloading and only unscoping)
5) Aim again --> gun is now magically reloaded, and no ammo is gone out of the inventory

**Comment by JaHollTV** [comment]
Expected Behavior
When i Scope and then press reload - the gun should start reloading

**Comment by Lorenzo0111** [comment]
Did you try the dev build? If yes could you provide a video while you test the plugin? 

Also please run /version QualityArmory in the video

**Comment by JaHollTV** [comment]
yes, bug also exists with dev-build: https://youtu.be/oGUobcE8fTw

So i just 
1) Aim
2) Shoot
3) Press F to Reload
4) Aim Again

Should be easy to reproduce for you. 


QA-Config-Options
enableReloadingWhenSwapToOffhand: true
enableReloadOnlyWhenSwapToOffhand: false
Swap-Reload-and-Shooting-Controls: false
allowGunReload: true

**Comment by LeoSenftleben** [comment]
I can confirm this issue: We also have this on our Server.

Please fix asap!!

**Comment by xCraimax** [comment]
Same thing for me actually!
How soon could this be fixed?
