### ISSUE TITLE
Plugin 70% broken

### ISSUE THREAD

**Issue by RedPxnda** [ZombieStriker/QualityArmory#53]
I run this plugin on my 1.14.4 server but most of the guns are broken. Most of the guns with automatic fire don’t automatically fire when I shift and left click. On versions 1.1.149+ The guns won’t even damage the entities I shoot.

**Comment by ZombieStriker** [comment]
The automatic weapons issue should be fixed in v1.1.152. If it still occurs on the newest version, could you try setting "ENABLE_DEBUG" to true, try to sneak and fire, and post the messages that appear in the console?
