### ISSUE TITLE
Bug in the plugin

### ISSUE THREAD

**Issue by Garielli27** [ZombieStriker/QualityArmory#533]
### Confirmations

- [X] I am using the latest plugin version with the required dependencies.
- [X] There isn't any open issue that shows my problem

### What happened?

When you pull out the check and exit the server, it causes damage to the players (a grenade explodes).
When the same actions are done to a Molotov cocktail, then it burns on the ground endlessly. Please fix this

### Expected Behaviour

.

### Plugins

.

### Server Version

1.16.5

**Comment by Lorenzo0111** [comment]
Can you record a video of the issue?
