### ISSUE TITLE
[Bug]: API not returning the guns ingame

### ISSUE THREAD

**Issue by CedricDeBlanck** [ZombieStriker/QualityArmory#534]
### Confirmations

- [X] I am using the latest plugin version with the required dependencies.
- [X] There isn't any open issue that shows my problem

### What happened?

Receiving the guns via Iterators.size(QualityArmory.getGuns()) in the api it returns 0 but i have 3 rows of guns if i use /qa shop ingame

### Expected Behaviour

I expect to receive the count 27 or if use QualityArmory.getGuns()  to receive a list of guns.

### Plugins

I don't think thats relevant.

### Server Version

1.18.2

### Relevant log output

```shell
No errors, nothing.
```

**Comment by Lorenzo0111** [comment]
Try printing the return of `QualityArmory.getGuns()` and see what it returns
