### ISSUE TITLE
QualityArmoryVehicles

### ISSUE THREAD

**Issue by RedPxnda** [ZombieStriker/QualityArmory#54]
In the Quality armory vehicles plugin, I can't seem to get the planes to work. It says press space to start flying but it doesn't fly. Also the resource pack doesn't work.

P.S. If this is the wrong place to talk about this, then sorry : P i couldn't find anywhere else.

**Comment by Ghost-chu** [comment]
Vehicles doesn't moving but sound was played.
1.15.2 confirmed

**Comment by ZombieStriker** [comment]
I've tested on 1.15.2, put fuel in the tank, and was able to fly the plane. Are there any errors in the console when this happens?

**Comment by Ghost-chu** [comment]
No any error, like the plugin Vehicles plugin, it just playing sound, the car can rotation, BUT just only can't move.

**Comment by siamneko** [comment]
I use Paper version git-Paper-243 (MC: 1.14.4)
Set "armor-stands-tick" to true
started with only two plugins, QualityArmoryｰVehicles and ProtocolLib, and tried
But, the called vehicle can rotate but cannot move
No error on console
Is support for 1.14.4 ongoing?

**Comment by ZombieStriker** [comment]
@siamneko 
First, is there fuel (*e.g. coal) in the tank of the vehicle?

If so, can you test the plugin on a regular spigot server?  If so, does that fix the problem? If it does, I'll try to see what else could be the problem with paperspigot.

**Comment by siamneko** [comment]
didn't know how to put fuel, so I came out at TAB / tried qav registerfuel
I had coal in main hand but it was not consumed
And the vehicle did not move
Tried with Spigot-56f8471-3e3818b (MC: 1.14.4) but vehicle did not move
started with only two plugins, QualityArmoryｰVehicles and ProtocolLib, and tried
The result was the same
What is the right way to add fuel

**Comment by ZombieStriker** [comment]
You add fuel to a vehicle by Shift+RMB on the vehicle, click the "tank" (the coal on the top right), and put the coal in the new GUI.

**Comment by siamneko** [comment]
Put the fuel
https://gyazo.com/df7de955ed9779a080f6e06b725ca334
But the vehicle did not move
Reducing plug-ins has no effect
same as spigot
what should I do?

**Comment by siamneko** [comment]
Moved, thank you
