### ISSUE TITLE
There are two critical bugs

### ISSUE THREAD

**Issue by yumjunstar** [ZombieStriker/QualityArmory#55]
First bug , When I'm holding a item with left hand and then press shift button to use iron sight, the left-handed item is gone just removed from the inventory
Second bug, When I die as soon as Reloading the gun, the gun will always be broken remaining [Reloading...] text next to the gun's name

**Comment by ZombieStriker** [comment]
Which version of QA are you using, and which mc update are you on? Are you on 1.15?

For the left-handed bug, that should not be possible (it should put the gun back in the main hand right when you move it to the offhand.). Are  there any errors in the console when this happens?

**Comment by yumjunstar** [comment]
> Which version of QA are you using, and which mc update are you on? Are you on 1.15?
> 
> For the left-handed bug, that should not be possible (it should put the gun back in the main hand right when you move it to the offhand.). Are there any errors in the console when this happens?

I'm using paper 1.15.1 and Qa version is 1.1.152 There are no error message on console
I'm saying "When I am holding any item (including gun) in left-hand and then I press Shift button to enable iron sight, the left-hand item will be removed" rather than "When I holding gun with left-hand"

Second problem is While reloading a gun If I die, the gun is broken

**Comment by Ghost-chu** [comment]
both problem confirmed on my server
1.1.154
