### ISSUE TITLE
[Feature]: Development-Method   gun.replace

### ISSUE THREAD

**Issue by JaHollTV** [ZombieStriker/QualityArmory#558]
### Confirmations

- [X] There isn't any other PR or issue regarding this.
- [X] This feature does not exist in the latest version.

### What is your request about?

New mechanic

### Description

For Developers it would be awesome to have a method to replace a gun.

Just something like "gun.replace(otherGun)".
Then for example the simple-aiming-animation(https://github.com/ZombieStriker/QualityArmory/issues/557) could be added by a Dev via the API :)

I think primary for QA-Extentions this Method would be awesome

**Comment by Lorenzo0111** [comment]
Could you explain better how this should work?

**Comment by JaHollTV** [comment]
My basic idea was to replace the itemStack of a gun. There is no option, so thought a method to replace a whole gun (which maybe overrides all attributes from the old gun with the attributes from the new gun) would be better.

But while I am thinking about that, perhaps it is not really needed right now. Like with the simple-aiming-animation-issue i will just suggest features when something comes into my mind.
If I really need some new developer-methods, i will request them as well.
