### ISSUE TITLE
[Bug]: RSC+TXTpack [autolink UPDATE]

### ISSUE THREAD

**Issue by GORECKIPL** [ZombieStriker/QualityArmory#559]
### Confirmations

- [X] I am using the latest plugin version with the required dependencies.
- [X] There isn't any open issue that shows my problem

### What happened?

I'm have problem with config file. 
In last line is link for rsc.github.zip file I'm have multiple resource pack own and from other creators. 
Why link from my own serwer is deleted and added rsc.github.zip 

### Expected Behaviour

Give normal config in .jar file 

### Plugins

PlaceholderAPI, NoteblockAPI ViaVersion, ViaBackguards, JukeBOX, SkyBlock, DecentHolograms (old HolographicDisplays), Skin Restorer, Vault, Dynmap, WorldEdit, WorldGuard, Multiverse-Core, Essentials, QualityArmory, Skript, AuthMe, Sign, VoiceChat, MyWorlds, Battlefield, CraftZ.

### Server Version

1.20.1

### Relevant log output

```shell
Nothing happened... Normal running console no ERRORS.
```

**Comment by Lorenzo0111** [comment]
The link you provided is not from my plugin. Make sure you downloaded the plugin from a trusted source such as this github page or from SpigotMC.

Also try disabling  `Enable_Creation_Of_Default_Files`
