### ISSUE TITLE
Dropping gun will duplicate that gun

### ISSUE THREAD

**Issue by AsVaidas** [ZombieStriker/QualityArmory#6]
When dropping a gun with more bullets than 1 it will duplicate a gun
The main reason is:
`enableVisableBulletCounts: true`
If the weapon has more bullets than one, the gun needs to be dropped with ctrl+q, otherwise it will duplicate that gun
Major bug
(Made a second post about this bug, because I made some testing, and haven't seen in the new update that this was fixed)

**Comment by ZombieStriker** [comment]
I believe I have fixed it in the new update (1.1.47). In it, if the player drops or interacts with a gun, it will now do a check to make sure there are no other instances other same gun in their inventory.

**Comment by AsVaidas** [comment]
Okay, it was fixed, but new issue
