### ISSUE TITLE
Durability

### ISSUE THREAD

**Issue by AguaDeLaMiseria** [ZombieStriker/QualityArmory#61]
Has title, the durability system doesn't work. Weapon's durability will stay in max durability no matter what. Hope you can fix it, great plugin!

**Comment by AguaDeLaMiseria** [comment]
Revamping this as I believe it is critical.

**Comment by ZombieStriker** [comment]
Is it still broken on the newest update with the same issue as the original post?

**Comment by AguaDeLaMiseria** [comment]
It seems to be working! Although there is a little detail when durability is 1000/1000, it won't get formatted like the other stats (GREEN: GREEN)  but like a default lore (purple), but looks functional. If anything, I will report. Thank  you.
