### ISSUE TITLE
Critical gun duplicate bug

### ISSUE THREAD

**Issue by yumjunstar** [ZombieStriker/QualityArmory#64]
Shoot the gun while crossing the Shift and F buttons. The gun will be copied. Please fix the bug quickly.

mc version paper spigot 1.15.2 paper-105
quality armory version 1.1.1.56 (There is no 1.1.1.57 version download link)
https://www.dropbox.com/s/5sxxpw8k1089u4x/2020-02-25%2019-14-21.flv?dl=0
See the video

**Comment by ZombieStriker** [comment]
This has been addressed in the most recent update.
