### ISSUE TITLE
Editing Guns

### ISSUE THREAD

**Issue by RedPxnda** [ZombieStriker/QualityArmory#67]
I have used the version 1.1.152 for a while because I have made edits to every single gun, and when I try to update, all of those changes get reset. The only thing that still works, is the invalid and gun particles option. I can still edit the guns, but It would be a pain to do it all again. Also, if I try to copy and paste the previous ones, it still doesn't work.

**Comment by Lorenzo0111** [comment]
You have to disable the default file creation inside the config.yml. The value is `Enable_Creation_Of_Default_Files`
