### ISSUE TITLE
Dropping a gun with bullets will make it without bullets

### ISSUE THREAD

**Issue by AsVaidas** [ZombieStriker/QualityArmory#7]
While having the option:
`enableVisableBulletCounts: true`
When dropping a gun, it will lose all of it's bullets, and then players can't shoot when picking up the gun

**Comment by ZombieStriker** [comment]
This should be fixed in the next update which should be released on Friday.  I'll reply to this issue when I release it.

**Comment by ZombieStriker** [comment]
This has been fixed in the new update.
