### ISSUE TITLE
LightSaber and other bullet or gun can open chests and doors locked by lwcx

### ISSUE THREAD

**Issue by yumjunstar** [ZombieStriker/QualityArmory#70]
This bug very critical for me and other user please fix this bug
LWCX author send me here The person who can fix this bug is you
QualityAmory version 1.1.158
LWCX verison 2.2.4-52f8c06
Paper 1.15.2-131

https://www.dropbox.com/s/x7qim20qd1suw3o/2020-03-15%2018-18-22.flv?dl=0

**Comment by ZombieStriker** [comment]
This error will be fixed in the next update.
