### ISSUE TITLE
Kevlar Vests

### ISSUE THREAD

**Issue by rethan2213** [ZombieStriker/QualityArmory#77]
I was wondering if you could disable kevlar vests, because every time someone shoots someone the first bullet does damage and all the rest were said to be blocked by the kevlar vest. I don't see anywhere to disable it but I hope there is one because this is crucial for my server!

**Comment by ZombieStriker** [comment]
Kevlar vests should no longer exist in QA. If they do, go into either your /misc/ or your /armor/ directories and delete all of the kevlar armor yml files.
