### ISSUE TITLE
Economy not enabled when getting gun from shop

### ISSUE THREAD

**Issue by LibbyLIB** [ZombieStriker/QualityArmory#85]
When I try to take a gun from the shop, it doesn't let me do it and it shows a message in full caps saying: ECONOMY NOT ENABLED PLEASE CONTACT OWNER. I can't find anything on the internet about this so I hope you can fix this.

Thanks

**Comment by nanohard** [comment]
You need a separate economy plugin. I suggest Liteconomy.

**Comment by Lorenzo0111** [comment]
You are probably missing Vault

**Comment by AvacadoWizard120** [comment]
> You are probably missing Vault

I have vault installed but it may not be the correct one, as the source I downloaded it from says that it hasn't been tested for the version of Minecraft I'm running. Would you mind linking me to vault?

**Comment by Lorenzo0111** [comment]
https://www.spigotmc.org/resources/vault.34315/

**Comment by AvacadoWizard120** [comment]
> https://www.spigotmc.org/resources/vault.34315/

I promise you I'm running this exact plugin from this exact source. I have vault, essentialsX, and quality armory.

**Comment by Lorenzo0111** [comment]
Are you able to join my discord server? https://to.lorenzo0111.me/discord
