### ISSUE TITLE
Problem whit resourcepack

### ISSUE THREAD

**Issue by blacklorem** [ZombieStriker/QualityArmory#88]
Good evening, I found a problem with your plugin, in the game I would use my own texture, then disable that plugin.
I tried to put on the plugin config file this option: "useDefaultResourcepack: false", but when I enter in the server it imposes the installation of the texture of QualityArmory, going to delete mine.

**Comment by FrozenBeard** [comment]
This isnt working for me either.

**Comment by Lorenzo0111** [comment]
Fixed in the latest version
